package schema

type WeaponData struct {
	SourceRowID             Fact[uint32]              `json:"sourceRowID"`
	IconID                  Fact[uint32]              `json:"iconID"`
	WeaponTypeID            Fact[uint16]              `json:"weaponTypeID"`
	WeaponTypeIDSFV         *Fact[uint16]             `json:"weaponTypeID-sfv,omitempty"`
	SortID                  Fact[uint32]              `json:"sortID"`
	SortIDSFV               *Fact[uint32]             `json:"sortID-sfv,omitempty"`
	SortGroupID             Fact[uint8]               `json:"sortGroupID"`
	SortGroupIDSFV          *Fact[uint8]              `json:"sortGroupID-sfv,omitempty"`
	ReinforceTypeID         Fact[int32]               `json:"reinforceTypeID"`
	ReinforceTypeIDSFV      *Fact[int32]              `json:"reinforceTypeID-sfv,omitempty"`
	GemMountType            Fact[uint8]               `json:"gemMountType"`
	GemMountTypeSFV         *Fact[uint8]              `json:"gemMountType-sfv,omitempty"`
	Weight                  Fact[float64]             `json:"weight"`
	WeightSFV               *Fact[float64]            `json:"weight-sfv,omitempty"`
	AttackPhysical          Fact[int32]               `json:"attackPhysical"`
	AttackPhysicalSFV       *Fact[int32]              `json:"attackPhysical-sfv,omitempty"`
	AttackMagic             Fact[int32]               `json:"attackMagic"`
	AttackMagicSFV          *Fact[int32]              `json:"attackMagic-sfv,omitempty"`
	AttackFire              Fact[int32]               `json:"attackFire"`
	AttackFireSFV           *Fact[int32]              `json:"attackFire-sfv,omitempty"`
	AttackLightning         Fact[int32]               `json:"attackLightning"`
	AttackLightningSFV      *Fact[int32]              `json:"attackLightning-sfv,omitempty"`
	AttackHoly              Fact[int32]               `json:"attackHoly"`
	AttackHolySFV           *Fact[int32]              `json:"attackHoly-sfv,omitempty"`
	AttackStamina           Fact[int32]               `json:"attackStamina"`
	AttackStaminaSFV        *Fact[int32]              `json:"attackStamina-sfv,omitempty"`
	GuardPhysical           Fact[int32]               `json:"guardPhysical"`
	GuardPhysicalSFV        *Fact[int32]              `json:"guardPhysical-sfv,omitempty"`
	GuardMagic              Fact[int32]               `json:"guardMagic"`
	GuardMagicSFV           *Fact[int32]              `json:"guardMagic-sfv,omitempty"`
	GuardFire               Fact[int32]               `json:"guardFire"`
	GuardFireSFV            *Fact[int32]              `json:"guardFire-sfv,omitempty"`
	GuardLightning          Fact[int32]               `json:"guardLightning"`
	GuardLightningSFV       *Fact[int32]              `json:"guardLightning-sfv,omitempty"`
	GuardHoly               Fact[int32]               `json:"guardHoly"`
	GuardHolySFV            *Fact[int32]              `json:"guardHoly-sfv,omitempty"`
	GuardBoost              Fact[int32]               `json:"guardBoost"`
	GuardBoostSFV           *Fact[int32]              `json:"guardBoost-sfv,omitempty"`
	RequiredStrength        Fact[int32]               `json:"requiredStrength"`
	RequiredStrengthSFV     *Fact[int32]              `json:"requiredStrength-sfv,omitempty"`
	RequiredDexterity       Fact[int32]               `json:"requiredDexterity"`
	RequiredDexteritySFV    *Fact[int32]              `json:"requiredDexterity-sfv,omitempty"`
	RequiredIntelligence    Fact[int32]               `json:"requiredIntelligence"`
	RequiredIntelligenceSFV *Fact[int32]              `json:"requiredIntelligence-sfv,omitempty"`
	RequiredFaith           Fact[int32]               `json:"requiredFaith"`
	RequiredFaithSFV        *Fact[int32]              `json:"requiredFaith-sfv,omitempty"`
	RequiredArcane          Fact[int32]               `json:"requiredArcane"`
	RequiredArcaneSFV       *Fact[int32]              `json:"requiredArcane-sfv,omitempty"`
	ScalingStrengthRaw      Fact[float64]             `json:"scalingStrengthRaw"`
	ScalingDexterityRaw     Fact[float64]             `json:"scalingDexterityRaw"`
	ScalingIntelligenceRaw  Fact[float64]             `json:"scalingIntelligenceRaw"`
	ScalingFaithRaw         Fact[float64]             `json:"scalingFaithRaw"`
	ScalingArcaneRaw        Fact[float64]             `json:"scalingArcaneRaw"`
	Critical                Fact[int32]               `json:"critical"`
	CriticalSFV             *Fact[int32]              `json:"critical-sfv,omitempty"`
	PassiveEffects          []WeaponPassiveEffectData `json:"passiveEffects"`
	DefaultAshOfWarID       Fact[int32]               `json:"defaultAshOfWarID"`
	DefaultAshOfWarIDSFV    *Fact[int32]              `json:"defaultAshOfWarID-sfv,omitempty"`
	SwordArtsName           Fact[string]              `json:"swordArtsName"`
	SwordArtsNameSFV        *Fact[string]             `json:"swordArtsName-sfv,omitempty"`
	IsInfusable             Fact[bool]                `json:"isInfusable"`
	IsInfusableSFV          *Fact[bool]               `json:"isInfusable-sfv,omitempty"`
	IsSomber                Fact[bool]                `json:"isSomber"`
	IsSomberSFV             *Fact[bool]               `json:"isSomber-sfv,omitempty"`
	MaxUpgrade              Fact[int32]               `json:"maxUpgrade"`
	MaxUpgradeSFV           *Fact[int32]              `json:"maxUpgrade-sfv,omitempty"`
	Warnings                Fact[[]string]            `json:"warnings"`
	RightHandEquipable      Fact[bool]                `json:"rightHandEquipable"`
	LeftHandEquipable       Fact[bool]                `json:"leftHandEquipable"`
	BothHandEquipable       Fact[bool]                `json:"bothHandEquipable"`
	ArrowSlotEquipable      Fact[bool]                `json:"arrowSlotEquipable"`
	BoltSlotEquipable       Fact[bool]                `json:"boltSlotEquipable"`
}

type WeaponPassiveEffectData struct {
	Kind       Fact[string] `json:"kind"`
	Source     Fact[string] `json:"source"`
	SpEffectID Fact[int32]  `json:"spEffectID"`
	Label      Fact[string] `json:"label"`
	Value      Fact[int32]  `json:"value"`
	Known      Fact[bool]   `json:"known"`
}
