// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {inventory} from '../models';
import {saveengine} from '../models';
import {appearance} from '../models';
import {application} from '../models';
import {world} from '../models';
import {equipment} from '../models';
import {schema} from '../models';
import {catalog} from '../models';
import {network} from '../models';
import {diagnostics} from '../models';
import {character} from '../models';
import {gamecatalog} from '../models';

export function AddItemsToContainers(arg1:string,arg2:number,arg3:Array<inventory.AddItemsRequestEntry>,arg4:boolean,arg5:string):Promise<saveengine.AddItemsToContainersResult>;

export function ApplyAppearancePreset(arg1:string,arg2:number,arg3:string,arg4:string):Promise<appearance.ApplyAppearancePresetResult>;

export function ApplyFavoritePreset(arg1:string,arg2:number,arg3:number,arg4:string):Promise<saveengine.ApplyFavoritePresetResult>;

export function ClearRecentFiles():Promise<void>;

export function CloseSave(arg1:string):Promise<void>;

export function DeleteFavoritePreset(arg1:string,arg2:number,arg3:string):Promise<saveengine.DeleteFavoritePresetResult>;

export function DiscardChanges(arg1:string,arg2:string):Promise<saveengine.DiscardChangesResult>;

export function DiscardRecoveryJournal(arg1:string):Promise<void>;

export function ExportRecoveryJournal(arg1:string,arg2:string):Promise<void>;

export function GetAppearancePresets(arg1:string,arg2:Array<string>):Promise<appearance.GetAppearancePresetsResult>;

export function GetApplicationInfo():Promise<application.GetApplicationInfoResult>;

export function GetBellBearings(arg1:string,arg2:number,arg3:string):Promise<world.GetBellBearingsResult>;

export function GetBosses(arg1:string,arg2:number):Promise<world.GetBossesResult>;

export function GetCharacterLoadout(arg1:string,arg2:number):Promise<equipment.GetCharacterLoadoutResult>;

export function GetCharacterProfile(arg1:string,arg2:number):Promise<saveengine.CharacterProfile>;

export function GetCharacterStats(arg1:string,arg2:number):Promise<saveengine.CharacterStats>;

export function GetColosseums(arg1:string,arg2:number):Promise<world.GetColosseumsResult>;

export function GetCookbooks(arg1:string,arg2:number,arg3:string):Promise<world.GetCookbooksResult>;

export function GetEquipment(arg1:string,arg2:number):Promise<saveengine.CharacterEquipment>;

export function GetEquipmentCandidates(arg1:string,arg2:number,arg3:string,arg4:string,arg5:number,arg6:number):Promise<equipment.GetEquipmentCandidatesResult>;

export function GetEquippedSpells(arg1:string,arg2:number):Promise<equipment.GetEquippedSpellsResult>;

export function GetFavoritePresets(arg1:string,arg2:any):Promise<saveengine.FavoritePresetsState>;

export function GetGestures(arg1:string,arg2:number,arg3:string):Promise<world.GetGesturesResult>;

export function GetGraces(arg1:string,arg2:number):Promise<world.GetGracesResult>;

export function GetInventory(arg1:string,arg2:number,arg3:string,arg4:number,arg5:number):Promise<inventory.GetInventoryResult>;

export function GetItemDatabase(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:Array<schema.ResourceRef>,arg6:string,arg7:number,arg8:number):Promise<catalog.GetItemDatabaseResult>;

export function GetItemVariants(arg1:string,arg2:string):Promise<catalog.GetItemVariantsResult>;

export function GetLoadedSave(arg1:string):Promise<saveengine.SessionInfo>;

export function GetMapRegions(arg1:string,arg2:number):Promise<world.GetMapRegionsResult>;

export function GetNetworkPresets(arg1:string):Promise<network.GetNetworkPresetsResult>;

export function GetNetworkSettings(arg1:string):Promise<network.GetNetworkSettingsResult>;

export function GetOperationHistory(arg1:string):Promise<saveengine.OperationHistory>;

export function GetOwnedItems(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:Array<schema.ResourceRef>,arg9:string,arg10:number,arg11:number):Promise<inventory.GetOwnedItemsResult>;

export function GetPhysickMixture(arg1:string,arg2:number):Promise<saveengine.CharacterPhysickMixture>;

export function GetPouchItems(arg1:string,arg2:number):Promise<saveengine.CharacterPouchItems>;

export function GetQuests(arg1:string,arg2:number,arg3:string,arg4:string):Promise<world.GetQuestsResult>;

export function GetQuickItems(arg1:string,arg2:number):Promise<saveengine.CharacterQuickItems>;

export function GetRecentFiles():Promise<Array<saveengine.RecentFile>>;

export function GetRecoveryJournal(arg1:string):Promise<saveengine.RecoveryJournalSummary>;

export function GetRecoveryJournals():Promise<Array<saveengine.RecoveryJournalSummary>>;

export function GetRegions(arg1:string,arg2:number):Promise<world.GetRegionsResult>;

export function GetResource(arg1:string,arg2:string):Promise<catalog.GetResourceResult>;

export function GetResourcePresentationSummaries(arg1:Array<catalog.ResourcePresentationIdentity>):Promise<catalog.GetResourcePresentationSummariesResult>;

export function GetResources(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number):Promise<catalog.GetResourcesResult>;

export function GetSafetyProfile():Promise<application.SafetyProfileResult>;

export function GetSaveCharacters(arg1:string):Promise<saveengine.SaveCharacters>;

export function GetSaveLifecycleSettings():Promise<saveengine.SaveLifecycleSettings>;

export function GetSaveValidationReport(arg1:string,arg2:number,arg3:string):Promise<diagnostics.GetSaveValidationReportResult>;

export function GetSpectralSteedAttires(arg1:string,arg2:number):Promise<world.GetSpectralSteedAttiresResult>;

export function GetStorage(arg1:string,arg2:number,arg3:string,arg4:number,arg5:number):Promise<inventory.GetStorageResult>;

export function GetSummoningPools(arg1:string,arg2:number):Promise<world.GetSummoningPoolsResult>;

export function GetTutorials(arg1:string,arg2:number,arg3:string):Promise<world.GetTutorialsResult>;

export function GetWhetblades(arg1:string,arg2:number,arg3:string):Promise<world.GetWhetbladesResult>;

export function GetWorldMutationCapabilities():Promise<world.GetWorldMutationCapabilitiesResult>;

export function LoadSave(arg1:string,arg2:string,arg3:string):Promise<saveengine.SessionInfo>;

export function LockAllSpectralSteedAttires(arg1:string,arg2:number,arg3:string):Promise<world.LockAllSpectralSteedAttiresResult>;

export function MoveOwnedItemsToInventory(arg1:string,arg2:number,arg3:Array<string>,arg4:string):Promise<saveengine.MoveOwnedItemsResult>;

export function MoveOwnedItemsToStorage(arg1:string,arg2:number,arg3:Array<string>,arg4:string):Promise<saveengine.MoveOwnedItemsResult>;

export function QuitApplication():Promise<void>;

export function RecordRecentFile(arg1:string):Promise<Array<saveengine.RecentFile>>;

export function RedoLastOperation(arg1:string,arg2:string):Promise<saveengine.HistoryMutationResult>;

export function RemoveOwnedItems(arg1:string,arg2:number,arg3:Array<string>,arg4:string):Promise<saveengine.RemoveOwnedItemsResult>;

export function RemoveRecentFile(arg1:string):Promise<Array<saveengine.RecentFile>>;

export function ReorderInventoryItems(arg1:string,arg2:number,arg3:string,arg4:Array<string>,arg5:number,arg6:string):Promise<inventory.ReorderInventoryItemsResult>;

export function RestoreRecoveryJournal(arg1:string):Promise<saveengine.SessionInfo>;

export function RevertOperation(arg1:string,arg2:string,arg3:string):Promise<saveengine.HistoryMutationResult>;

export function Save(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<saveengine.SaveLifecycleResult>;

export function SaveAs(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean,arg6:string):Promise<saveengine.SaveLifecycleResult>;

export function SelectSaveFile():Promise<string>;

export function SelectSaveTarget(arg1:string):Promise<string>;

export function SetBellBearingUnlocked(arg1:string,arg2:number,arg3:string,arg4:string,arg5:boolean,arg6:string):Promise<world.SetBellBearingUnlockedResult>;

export function SetBossDefeated(arg1:string,arg2:number,arg3:string,arg4:string,arg5:boolean,arg6:string):Promise<world.SetBossDefeatedResult>;

export function SetCharacterGender(arg1:string,arg2:number,arg3:number,arg4:string):Promise<character.SetCharacterGenderResult>;

export function SetCharacterName(arg1:string,arg2:number,arg3:string,arg4:string):Promise<saveengine.SetCharacterNameResult>;

export function SetCharacterRunes(arg1:string,arg2:number,arg3:number,arg4:string):Promise<saveengine.SetCharacterRunesResult>;

export function SetCharacterStartingClass(arg1:string,arg2:number,arg3:number,arg4:boolean,arg5:string):Promise<saveengine.SetCharacterStartingClassResult>;

export function SetCharacterStats(arg1:string,arg2:number,arg3:saveengine.CharacterAttributes,arg4:string,arg5:string):Promise<saveengine.SetCharacterStatsResult>;

export function SetColosseumUnlocked(arg1:string,arg2:number,arg3:string,arg4:string,arg5:boolean,arg6:string):Promise<world.SetColosseumUnlockedResult>;

export function SetCookbookUnlocked(arg1:string,arg2:number,arg3:string,arg4:string,arg5:boolean,arg6:string):Promise<world.SetCookbookUnlockedResult>;

export function SetEquippedArmaments(arg1:string,arg2:number,arg3:Array<any>,arg4:string):Promise<equipment.SetEquippedArmamentsResult>;

export function SetEquippedArmor(arg1:string,arg2:number,arg3:Array<any>,arg4:string):Promise<equipment.SetEquippedArmorResult>;

export function SetEquippedSpells(arg1:string,arg2:number,arg3:Array<schema.ResourceRef>,arg4:string):Promise<equipment.SetEquippedSpellsResult>;

export function SetEquippedTalismans(arg1:string,arg2:number,arg3:Array<string>,arg4:string):Promise<equipment.SetEquippedTalismansResult>;

export function SetFavoritePreset(arg1:string,arg2:number,arg3:number,arg4:string):Promise<saveengine.SetFavoritePresetResult>;

export function SetFogOfWarRemoved(arg1:string,arg2:number,arg3:boolean,arg4:string):Promise<world.SetFogOfWarRemovedResult>;

export function SetGestureUnlocked(arg1:string,arg2:number,arg3:string,arg4:string,arg5:boolean,arg6:string):Promise<world.SetGestureUnlockedResult>;

export function SetGraceVisited(arg1:string,arg2:number,arg3:string,arg4:string,arg5:boolean,arg6:string):Promise<world.SetGraceVisitedResult>;

export function SetMapRegionRevealed(arg1:string,arg2:number,arg3:string,arg4:string,arg5:boolean,arg6:string):Promise<world.SetMapRegionRevealedResult>;

export function SetNetworkSettings(arg1:string,arg2:gamecatalog.NetworkParamValues,arg3:string):Promise<saveengine.SetNetworkSettingsResult>;

export function SetOwnedItemQuantity(arg1:string,arg2:number,arg3:string,arg4:number,arg5:string):Promise<saveengine.SetOwnedItemQuantityResult>;

export function SetPhysickMixture(arg1:string,arg2:number,arg3:Array<schema.ResourceRef>,arg4:string):Promise<equipment.SetPhysickMixtureResult>;

export function SetPouchItems(arg1:string,arg2:number,arg3:Array<any>,arg4:string):Promise<equipment.SetPouchItemsResult>;

export function SetQuestStep(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<world.SetQuestStepResult>;

export function SetQuickItems(arg1:string,arg2:number,arg3:Array<any>,arg4:string):Promise<equipment.SetQuickItemsResult>;

export function SetRegionUnlocked(arg1:string,arg2:number,arg3:string,arg4:string,arg5:boolean,arg6:string):Promise<world.SetRegionUnlockedResult>;

export function SetSafetyProfile(arg1:string):Promise<application.SafetyProfileResult>;

export function SetSaveLifecycleSettings(arg1:number):Promise<saveengine.SaveLifecycleSettings>;

export function SetSpectralSteedAttire(arg1:string,arg2:number,arg3:string,arg4:string):Promise<world.SetSpectralSteedAttireResult>;

export function SetSummoningPoolActivated(arg1:string,arg2:number,arg3:string,arg4:string,arg5:boolean,arg6:string):Promise<world.SetSummoningPoolActivatedResult>;

export function SetTutorialUnlocked(arg1:string,arg2:number,arg3:string,arg4:string,arg5:boolean,arg6:string):Promise<world.SetTutorialUnlockedResult>;

export function SetWhetbladeUnlocked(arg1:string,arg2:number,arg3:string,arg4:string,arg5:boolean,arg6:string):Promise<world.SetWhetbladeUnlockedResult>;

export function UndoLastOperation(arg1:string,arg2:string):Promise<saveengine.HistoryMutationResult>;

export function ValidateReviewChanges(arg1:string,arg2:string):Promise<saveengine.ReviewValidationResult>;
