// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearRecentFiles() {
  return window['go']['desktop']['Bridge']['ClearRecentFiles']();
}

export function CloseSave(arg1) {
  return window['go']['desktop']['Bridge']['CloseSave'](arg1);
}

export function DiscardChanges(arg1, arg2) {
  return window['go']['desktop']['Bridge']['DiscardChanges'](arg1, arg2);
}

export function DiscardRecoveryJournal(arg1) {
  return window['go']['desktop']['Bridge']['DiscardRecoveryJournal'](arg1);
}

export function ExportRecoveryJournal(arg1, arg2) {
  return window['go']['desktop']['Bridge']['ExportRecoveryJournal'](arg1, arg2);
}

export function GetApplicationInfo() {
  return window['go']['desktop']['Bridge']['GetApplicationInfo']();
}

export function GetCharacterLoadout(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetCharacterLoadout'](arg1, arg2);
}

export function GetCharacterProfile(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetCharacterProfile'](arg1, arg2);
}

export function GetCharacterStats(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetCharacterStats'](arg1, arg2);
}

export function GetEquipment(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetEquipment'](arg1, arg2);
}

export function GetEquippedSpells(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetEquippedSpells'](arg1, arg2);
}

export function GetInventory(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['desktop']['Bridge']['GetInventory'](arg1, arg2, arg3, arg4, arg5);
}

export function GetItemVariants(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetItemVariants'](arg1, arg2);
}

export function GetLoadedSave(arg1) {
  return window['go']['desktop']['Bridge']['GetLoadedSave'](arg1);
}

export function GetOperationHistory(arg1) {
  return window['go']['desktop']['Bridge']['GetOperationHistory'](arg1);
}

export function GetPhysickMixture(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetPhysickMixture'](arg1, arg2);
}

export function GetPouchItems(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetPouchItems'](arg1, arg2);
}

export function GetQuickItems(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetQuickItems'](arg1, arg2);
}

export function GetRecentFiles() {
  return window['go']['desktop']['Bridge']['GetRecentFiles']();
}

export function GetRecoveryJournal(arg1) {
  return window['go']['desktop']['Bridge']['GetRecoveryJournal'](arg1);
}

export function GetRecoveryJournals() {
  return window['go']['desktop']['Bridge']['GetRecoveryJournals']();
}

export function GetResource(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetResource'](arg1, arg2);
}

export function GetResourcePresentationSummaries(arg1) {
  return window['go']['desktop']['Bridge']['GetResourcePresentationSummaries'](arg1);
}

export function GetResources(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['desktop']['Bridge']['GetResources'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetSaveCharacters(arg1) {
  return window['go']['desktop']['Bridge']['GetSaveCharacters'](arg1);
}

export function GetSaveLifecycleSettings() {
  return window['go']['desktop']['Bridge']['GetSaveLifecycleSettings']();
}

export function GetSaveValidationReport(arg1, arg2, arg3) {
  return window['go']['desktop']['Bridge']['GetSaveValidationReport'](arg1, arg2, arg3);
}

export function GetStorage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['desktop']['Bridge']['GetStorage'](arg1, arg2, arg3, arg4, arg5);
}

export function LoadSave(arg1, arg2, arg3) {
  return window['go']['desktop']['Bridge']['LoadSave'](arg1, arg2, arg3);
}

export function QuitApplication() {
  return window['go']['desktop']['Bridge']['QuitApplication']();
}

export function RecordRecentFile(arg1) {
  return window['go']['desktop']['Bridge']['RecordRecentFile'](arg1);
}

export function RedoLastOperation(arg1, arg2) {
  return window['go']['desktop']['Bridge']['RedoLastOperation'](arg1, arg2);
}

export function RemoveRecentFile(arg1) {
  return window['go']['desktop']['Bridge']['RemoveRecentFile'](arg1);
}

export function RestoreRecoveryJournal(arg1) {
  return window['go']['desktop']['Bridge']['RestoreRecoveryJournal'](arg1);
}

export function RevertOperation(arg1, arg2, arg3) {
  return window['go']['desktop']['Bridge']['RevertOperation'](arg1, arg2, arg3);
}

export function Save(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['desktop']['Bridge']['Save'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveAs(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['desktop']['Bridge']['SaveAs'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SelectSaveFile() {
  return window['go']['desktop']['Bridge']['SelectSaveFile']();
}

export function SelectSaveTarget(arg1) {
  return window['go']['desktop']['Bridge']['SelectSaveTarget'](arg1);
}

export function SetSaveLifecycleSettings(arg1) {
  return window['go']['desktop']['Bridge']['SetSaveLifecycleSettings'](arg1);
}

export function UndoLastOperation(arg1, arg2) {
  return window['go']['desktop']['Bridge']['UndoLastOperation'](arg1, arg2);
}

export function ValidateReviewChanges(arg1, arg2) {
  return window['go']['desktop']['Bridge']['ValidateReviewChanges'](arg1, arg2);
}
