// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';
import {saveengine} from '../models';
import {inventory} from '../models';

export function CloseSave(arg1:string):Promise<void>;

export function GetApplicationInfo():Promise<application.GetApplicationInfoResult>;

export function GetCharacterProfile(arg1:string,arg2:number):Promise<saveengine.CharacterProfile>;

export function GetCharacterStats(arg1:string,arg2:number):Promise<saveengine.CharacterStats>;

export function GetInventory(arg1:string,arg2:number,arg3:string,arg4:number,arg5:number):Promise<inventory.GetInventoryResult>;

export function GetLoadedSave(arg1:string):Promise<saveengine.SessionInfo>;

export function GetSaveCharacters(arg1:string):Promise<saveengine.SaveCharacters>;

export function GetStorage(arg1:string,arg2:number,arg3:string,arg4:number,arg5:number):Promise<inventory.GetStorageResult>;

export function LoadSave(arg1:string,arg2:string):Promise<saveengine.SessionInfo>;
