// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSave(arg1) {
  return window['go']['desktop']['Bridge']['CloseSave'](arg1);
}

export function GetApplicationInfo() {
  return window['go']['desktop']['Bridge']['GetApplicationInfo']();
}

export function GetCharacterProfile(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetCharacterProfile'](arg1, arg2);
}

export function GetCharacterStats(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetCharacterStats'](arg1, arg2);
}

export function GetLoadedSave(arg1) {
  return window['go']['desktop']['Bridge']['GetLoadedSave'](arg1);
}

export function GetSaveCharacters(arg1) {
  return window['go']['desktop']['Bridge']['GetSaveCharacters'](arg1);
}

export function LoadSave(arg1, arg2) {
  return window['go']['desktop']['Bridge']['LoadSave'](arg1, arg2);
}
