// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';

export function GetApplicationInfo():Promise<application.GetApplicationInfoResult>;
