// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItemsToContainers(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['desktop']['Bridge']['AddItemsToContainers'](arg1, arg2, arg3, arg4, arg5);
}

export function ApplyAppearancePreset(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['Bridge']['ApplyAppearancePreset'](arg1, arg2, arg3, arg4);
}

export function ApplyFavoritePreset(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['Bridge']['ApplyFavoritePreset'](arg1, arg2, arg3, arg4);
}

export function ClearRecentFiles() {
  return window['go']['desktop']['Bridge']['ClearRecentFiles']();
}

export function CloseSave(arg1) {
  return window['go']['desktop']['Bridge']['CloseSave'](arg1);
}

export function DeleteFavoritePreset(arg1, arg2, arg3) {
  return window['go']['desktop']['Bridge']['DeleteFavoritePreset'](arg1, arg2, arg3);
}

export function DiscardChanges(arg1, arg2) {
  return window['go']['desktop']['Bridge']['DiscardChanges'](arg1, arg2);
}

export function DiscardRecoveryJournal(arg1) {
  return window['go']['desktop']['Bridge']['DiscardRecoveryJournal'](arg1);
}

export function ExportRecoveryJournal(arg1, arg2) {
  return window['go']['desktop']['Bridge']['ExportRecoveryJournal'](arg1, arg2);
}

export function GetAppearancePresets(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetAppearancePresets'](arg1, arg2);
}

export function GetApplicationInfo() {
  return window['go']['desktop']['Bridge']['GetApplicationInfo']();
}

export function GetBellBearings(arg1, arg2, arg3) {
  return window['go']['desktop']['Bridge']['GetBellBearings'](arg1, arg2, arg3);
}

export function GetBosses(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetBosses'](arg1, arg2);
}

export function GetCharacterLoadout(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetCharacterLoadout'](arg1, arg2);
}

export function GetCharacterProfile(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetCharacterProfile'](arg1, arg2);
}

export function GetCharacterStats(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetCharacterStats'](arg1, arg2);
}

export function GetColosseums(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetColosseums'](arg1, arg2);
}

export function GetCookbooks(arg1, arg2, arg3) {
  return window['go']['desktop']['Bridge']['GetCookbooks'](arg1, arg2, arg3);
}

export function GetEquipment(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetEquipment'](arg1, arg2);
}

export function GetEquipmentCandidates(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['desktop']['Bridge']['GetEquipmentCandidates'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetEquippedSpells(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetEquippedSpells'](arg1, arg2);
}

export function GetFavoritePresets(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetFavoritePresets'](arg1, arg2);
}

export function GetGestures(arg1, arg2, arg3) {
  return window['go']['desktop']['Bridge']['GetGestures'](arg1, arg2, arg3);
}

export function GetGraces(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetGraces'](arg1, arg2);
}

export function GetInventory(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['desktop']['Bridge']['GetInventory'](arg1, arg2, arg3, arg4, arg5);
}

export function GetItemDatabase(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['desktop']['Bridge']['GetItemDatabase'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function GetItemVariants(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetItemVariants'](arg1, arg2);
}

export function GetLoadedSave(arg1) {
  return window['go']['desktop']['Bridge']['GetLoadedSave'](arg1);
}

export function GetMapRegions(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetMapRegions'](arg1, arg2);
}

export function GetOperationHistory(arg1) {
  return window['go']['desktop']['Bridge']['GetOperationHistory'](arg1);
}

export function GetOwnedItems(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['desktop']['Bridge']['GetOwnedItems'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function GetPhysickMixture(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetPhysickMixture'](arg1, arg2);
}

export function GetPouchItems(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetPouchItems'](arg1, arg2);
}

export function GetQuests(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['Bridge']['GetQuests'](arg1, arg2, arg3, arg4);
}

export function GetQuickItems(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetQuickItems'](arg1, arg2);
}

export function GetRecentFiles() {
  return window['go']['desktop']['Bridge']['GetRecentFiles']();
}

export function GetRecoveryJournal(arg1) {
  return window['go']['desktop']['Bridge']['GetRecoveryJournal'](arg1);
}

export function GetRecoveryJournals() {
  return window['go']['desktop']['Bridge']['GetRecoveryJournals']();
}

export function GetRegions(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetRegions'](arg1, arg2);
}

export function GetResource(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetResource'](arg1, arg2);
}

export function GetResourcePresentationSummaries(arg1) {
  return window['go']['desktop']['Bridge']['GetResourcePresentationSummaries'](arg1);
}

export function GetResources(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['desktop']['Bridge']['GetResources'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetSafetyProfile() {
  return window['go']['desktop']['Bridge']['GetSafetyProfile']();
}

export function GetSaveCharacters(arg1) {
  return window['go']['desktop']['Bridge']['GetSaveCharacters'](arg1);
}

export function GetSaveLifecycleSettings() {
  return window['go']['desktop']['Bridge']['GetSaveLifecycleSettings']();
}

export function GetSaveValidationReport(arg1, arg2, arg3) {
  return window['go']['desktop']['Bridge']['GetSaveValidationReport'](arg1, arg2, arg3);
}

export function GetSpectralSteedAttires(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetSpectralSteedAttires'](arg1, arg2);
}

export function GetStorage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['desktop']['Bridge']['GetStorage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSummoningPools(arg1, arg2) {
  return window['go']['desktop']['Bridge']['GetSummoningPools'](arg1, arg2);
}

export function GetTutorials(arg1, arg2, arg3) {
  return window['go']['desktop']['Bridge']['GetTutorials'](arg1, arg2, arg3);
}

export function GetWhetblades(arg1, arg2, arg3) {
  return window['go']['desktop']['Bridge']['GetWhetblades'](arg1, arg2, arg3);
}

export function LoadSave(arg1, arg2, arg3) {
  return window['go']['desktop']['Bridge']['LoadSave'](arg1, arg2, arg3);
}

export function MoveOwnedItemsToInventory(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['Bridge']['MoveOwnedItemsToInventory'](arg1, arg2, arg3, arg4);
}

export function MoveOwnedItemsToStorage(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['Bridge']['MoveOwnedItemsToStorage'](arg1, arg2, arg3, arg4);
}

export function QuitApplication() {
  return window['go']['desktop']['Bridge']['QuitApplication']();
}

export function RecordRecentFile(arg1) {
  return window['go']['desktop']['Bridge']['RecordRecentFile'](arg1);
}

export function RedoLastOperation(arg1, arg2) {
  return window['go']['desktop']['Bridge']['RedoLastOperation'](arg1, arg2);
}

export function RemoveOwnedItems(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['Bridge']['RemoveOwnedItems'](arg1, arg2, arg3, arg4);
}

export function RemoveRecentFile(arg1) {
  return window['go']['desktop']['Bridge']['RemoveRecentFile'](arg1);
}

export function ReorderInventoryItems(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['desktop']['Bridge']['ReorderInventoryItems'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RestoreRecoveryJournal(arg1) {
  return window['go']['desktop']['Bridge']['RestoreRecoveryJournal'](arg1);
}

export function RevertOperation(arg1, arg2, arg3) {
  return window['go']['desktop']['Bridge']['RevertOperation'](arg1, arg2, arg3);
}

export function Save(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['desktop']['Bridge']['Save'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveAs(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['desktop']['Bridge']['SaveAs'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SelectSaveFile() {
  return window['go']['desktop']['Bridge']['SelectSaveFile']();
}

export function SelectSaveTarget(arg1) {
  return window['go']['desktop']['Bridge']['SelectSaveTarget'](arg1);
}

export function SetCharacterGender(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['Bridge']['SetCharacterGender'](arg1, arg2, arg3, arg4);
}

export function SetCharacterName(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['Bridge']['SetCharacterName'](arg1, arg2, arg3, arg4);
}

export function SetCharacterRunes(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['Bridge']['SetCharacterRunes'](arg1, arg2, arg3, arg4);
}

export function SetCharacterStartingClass(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['desktop']['Bridge']['SetCharacterStartingClass'](arg1, arg2, arg3, arg4, arg5);
}

export function SetCharacterStats(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['desktop']['Bridge']['SetCharacterStats'](arg1, arg2, arg3, arg4, arg5);
}

export function SetEquippedArmaments(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['Bridge']['SetEquippedArmaments'](arg1, arg2, arg3, arg4);
}

export function SetEquippedArmor(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['Bridge']['SetEquippedArmor'](arg1, arg2, arg3, arg4);
}

export function SetEquippedSpells(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['Bridge']['SetEquippedSpells'](arg1, arg2, arg3, arg4);
}

export function SetEquippedTalismans(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['Bridge']['SetEquippedTalismans'](arg1, arg2, arg3, arg4);
}

export function SetFavoritePreset(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['Bridge']['SetFavoritePreset'](arg1, arg2, arg3, arg4);
}

export function SetOwnedItemQuantity(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['desktop']['Bridge']['SetOwnedItemQuantity'](arg1, arg2, arg3, arg4, arg5);
}

export function SetPhysickMixture(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['Bridge']['SetPhysickMixture'](arg1, arg2, arg3, arg4);
}

export function SetPouchItems(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['Bridge']['SetPouchItems'](arg1, arg2, arg3, arg4);
}

export function SetQuickItems(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['Bridge']['SetQuickItems'](arg1, arg2, arg3, arg4);
}

export function SetSafetyProfile(arg1) {
  return window['go']['desktop']['Bridge']['SetSafetyProfile'](arg1);
}

export function SetSaveLifecycleSettings(arg1) {
  return window['go']['desktop']['Bridge']['SetSaveLifecycleSettings'](arg1);
}

export function UndoLastOperation(arg1, arg2) {
  return window['go']['desktop']['Bridge']['UndoLastOperation'](arg1, arg2);
}

export function ValidateReviewChanges(arg1, arg2) {
  return window['go']['desktop']['Bridge']['ValidateReviewChanges'](arg1, arg2);
}
