import {useEffect, useState, useMemo} from 'react';
import {GetCharacter, RemoveItemsFromCharacter} from '../../wailsjs/go/main/App';
import {vm} from '../../wailsjs/go/models';
import {CategorySelect} from './CategorySelect';

interface InventoryTabProps {
    charIndex: number;
    inventoryVersion: number;
    columnVisibility: {
        id: boolean;
        category: boolean;
    };
    showFlaggedItems: boolean;
    category: string;
    setCategory: (value: string) => void;
}

export function InventoryTab({ charIndex, inventoryVersion, columnVisibility, showFlaggedItems, category, setCategory }: InventoryTabProps) {
    const [search, setSearch] = useState('');
    const [charInventory, setCharInventory] = useState<vm.ItemViewModel[]>([]);
    const [charStorage, setCharStorage] = useState<vm.ItemViewModel[]>([]);
    const [loading, setLoading] = useState(false);
    
    // Sorting state
    const [sortCol, setSortCol] = useState<string>('name');
    const [sortDir, setSortDir] = useState<'asc' | 'desc'>('asc');

    const [selectedIcon, setSelectedIcon] = useState<{name: string, path: string} | null>(null);
    const [isSaving, setIsSaving] = useState(false);

    // Local state for edited quantities
    const [editedInv, setEditedInv] = useState<Record<number, number>>({});
    const [editedStorage, setEditedStorage] = useState<Record<number, number>>({});

    // Selection + remove
    const [selectedKeys, setSelectedKeys] = useState<Set<string>>(new Set());
    const [removeModal, setRemoveModal] = useState<{handles: number[], names: string[]} | null>(null);
    const [isRemoving, setIsRemoving] = useState(false);
    const [brokenIcons, setBrokenIcons] = useState<Set<string>>(new Set());

    const toggleSelect = (key: string) => {
        setSelectedKeys(prev => {
            const next = new Set(prev);
            if (next.has(key)) next.delete(key); else next.add(key);
            return next;
        });
    };

    const toggleSelectAll = () => {
        if (selectedKeys.size === filteredOwnedItems.length && filteredOwnedItems.length > 0) {
            setSelectedKeys(new Set());
        } else {
            setSelectedKeys(new Set(filteredOwnedItems.map(i => rowKey(i))));
        }
    };

    const handleRemoveSelected = () => {
        const items = filteredOwnedItems.filter(i => selectedKeys.has(rowKey(i)));
        const handles = items.flatMap(i => [i.invHandle, i.storageHandle].filter(h => h !== 0));
        setRemoveModal({ handles, names: items.map(i => i.name) });
    };

    const confirmRemove = async (fromInventory: boolean, fromStorage: boolean) => {
        if (!removeModal || isRemoving) return;
        setIsRemoving(true);
        try {
            await RemoveItemsFromCharacter(charIndex, removeModal.handles, fromInventory, fromStorage);
            setSelectedKeys(new Set());
            setRemoveModal(null);
            // Reload inventory
            const char = await GetCharacter(charIndex);
            if (char) { setCharInventory(char.inventory || []); setCharStorage(char.storage || []); }
        } catch (err) {
            alert('Remove failed: ' + err);
        } finally {
            setIsRemoving(false);
        }
    };

    const handleQtyChange = (handle: number, value: string, type: 'inv' | 'storage', max: number) => {
        const qty = parseInt(value) || 0;
        const safeQty = Math.min(Math.max(0, qty), max);
        
        if (type === 'inv') {
            setEditedInv(prev => ({ ...prev, [handle]: safeQty }));
        } else {
            setEditedStorage(prev => ({ ...prev, [handle]: safeQty }));
        }
    };

    const saveChanges = async () => {
        if (isSaving) return;
        setIsSaving(true);
        try {
            const char = await GetCharacter(charIndex);
            if (!char) return;

            // Apply local edits to the character VM
            char.inventory = char.inventory.map(item => ({
                ...item,
                quantity: editedInv[item.handle] !== undefined ? editedInv[item.handle] : item.quantity
            }));
            char.storage = char.storage.map(item => ({
                ...item,
                quantity: editedStorage[item.handle] !== undefined ? editedStorage[item.handle] : item.quantity
            }));

            // @ts-ignore - SaveCharacter is generated by Wails
            await window.go.main.App.SaveCharacter(charIndex, char);
            
            // Refresh data
            const updatedChar = await GetCharacter(charIndex);
            setCharInventory(updatedChar?.inventory || []);
            setCharStorage(updatedChar?.storage || []);
            setEditedInv({});
            setEditedStorage({});
            
        } catch (err) {
            console.error("Failed to save inventory changes:", err);
        } finally {
            setIsSaving(false);
        }
    };

    type MergedItem = {
        id: number; name: string; category: string; subCategory: string;
        nonStackable: boolean; inInventory: boolean; inStorage: boolean;
        invHandle: number; storageHandle: number;
        invQty: number; storageQty: number;
        maxInv: number; maxStorage: number; maxUpgrade: number; currentUpgrade: number; iconPath: string;
        flags: string[];
    };

    const rowKey = (item: MergedItem) => item.nonStackable ? `h-${item.invHandle || item.storageHandle}` : `s-${item.id}`;

    // Build item list for display.
    // Non-stackable (maxInventory <= 1): one row per handle — consolidated across both locations.
    // Stackable (maxInventory > 1): merged by item ID — one row with both inv and storage qty.
    const mergedOwnedItems = (() => {
        const nonStackableMap = new Map<number, MergedItem>();
        const stackableMap = new Map<number, MergedItem>();

        charInventory.forEach(item => {
            if (item.maxInventory <= 1) {
                nonStackableMap.set(item.handle, {
                    id: item.id, name: item.name,
                    category: item.category, subCategory: item.subCategory,
                    nonStackable: true, inInventory: true, inStorage: false,
                    invHandle: item.handle, storageHandle: 0,
                    invQty: 1, storageQty: 0,
                    maxInv: item.maxInventory, maxStorage: item.maxStorage,
                    maxUpgrade: item.maxUpgrade, currentUpgrade: item.currentUpgrade ?? 0, iconPath: item.iconPath,
                    flags: item.flags ?? [],
                });
            } else {
                stackableMap.set(item.id, {
                    id: item.id, name: item.name,
                    category: item.category, subCategory: item.subCategory,
                    nonStackable: false, inInventory: true, inStorage: false,
                    invHandle: item.handle, storageHandle: 0,
                    invQty: item.quantity, storageQty: 0,
                    maxInv: item.maxInventory, maxStorage: item.maxStorage,
                    maxUpgrade: item.maxUpgrade, currentUpgrade: item.currentUpgrade ?? 0, iconPath: item.iconPath,
                    flags: item.flags ?? [],
                });
            }
        });

        charStorage.forEach(item => {
            if (item.maxInventory <= 1) {
                const existing = nonStackableMap.get(item.handle);
                if (existing) {
                    existing.inStorage = true;
                    existing.storageQty = 1;
                } else {
                    nonStackableMap.set(item.handle, {
                        id: item.id, name: item.name,
                        category: item.category, subCategory: item.subCategory,
                        nonStackable: true, inInventory: false, inStorage: true,
                        invHandle: 0, storageHandle: item.handle,
                        invQty: 0, storageQty: 1,
                        maxInv: item.maxInventory, maxStorage: item.maxStorage,
                        maxUpgrade: item.maxUpgrade, currentUpgrade: item.currentUpgrade ?? 0, iconPath: item.iconPath,
                        flags: item.flags ?? [],
                    });
                }
            } else {
                const existing = stackableMap.get(item.id);
                if (existing) {
                    existing.inStorage = true;
                    existing.storageHandle = item.handle;
                    existing.storageQty = item.quantity;
                } else {
                    stackableMap.set(item.id, {
                        id: item.id, name: item.name,
                        category: item.category, subCategory: item.subCategory,
                        nonStackable: false, inInventory: false, inStorage: true,
                        invHandle: 0, storageHandle: item.handle,
                        invQty: 0, storageQty: item.quantity,
                        maxInv: item.maxInventory, maxStorage: item.maxStorage,
                        maxUpgrade: item.maxUpgrade, currentUpgrade: item.currentUpgrade ?? 0, iconPath: item.iconPath,
                        flags: item.flags ?? [],
                    });
                }
            }
        });

        return [...Array.from(nonStackableMap.values()), ...Array.from(stackableMap.values())];
    })();

    const handleImageError = (iconPath: string) => {
        setBrokenIcons(prev => new Set(prev).add(iconPath));
    };

    useEffect(() => {
        setLoading(true);
        GetCharacter(charIndex).then(res => {
            setCharInventory(res?.inventory || []);
            setCharStorage(res?.storage || []);
        }).finally(() => setLoading(false));
    }, [charIndex, inventoryVersion]);

    const handleSort = (col: string) => {
        if (sortCol === col) {
            setSortDir(sortDir === 'asc' ? 'desc' : 'asc');
        } else {
            setSortCol(col);
            setSortDir('asc');
        }
    };

    const sortItems = (items: MergedItem[]) => {
        return [...items].sort((a, b) => {
            let valA: string | number = 0;
            let valB: string | number = 0;

            if (sortCol === 'maxUpgrade') {
                valA = a.maxUpgrade || 0;
                valB = b.maxUpgrade || 0;
            } else if (sortCol === 'currentUpgrade') {
                valA = a.currentUpgrade || 0;
                valB = b.currentUpgrade || 0;
            } else {
                const rawA = a[sortCol as keyof MergedItem];
                const rawB = b[sortCol as keyof MergedItem];
                if (typeof rawA === 'string' && typeof rawB === 'string') {
                    valA = rawA.toLowerCase();
                    valB = rawB.toLowerCase();
                } else if (typeof rawA === 'number' && typeof rawB === 'number') {
                    valA = rawA;
                    valB = rawB;
                }
            }

            if (valA < valB) return sortDir === 'asc' ? -1 : 1;
            if (valA > valB) return sortDir === 'asc' ? 1 : -1;
            return 0;
        });
    };

    const filteredOwnedItems = sortItems(mergedOwnedItems.filter(item => {
        if (!showFlaggedItems && item.flags?.length > 0) return false;
        const matchesSearch = item.name.toLowerCase().includes(search.toLowerCase()) ||
                            item.id.toString(16).toLowerCase().includes(search.toLowerCase());

        if (category === 'all') return matchesSearch && item.subCategory !== 'key_items';

        return item.subCategory === category && matchesSearch;
    }));

    const SortIndicator = ({ col }: { col: string }) => {
        if (sortCol !== col) return <span className="ml-1 opacity-20">↕</span>;
        return <span className="ml-1 text-primary">{sortDir === 'asc' ? '↑' : '↓'}</span>;
    };

    return (
        <div className="flex-1 flex flex-col min-h-0 space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-700">
            {/* Remove Confirm Modal */}
            {removeModal && (
                <div className="fixed inset-0 z-[110] flex items-center justify-center bg-background/80 backdrop-blur-sm animate-in fade-in duration-300">
                    <div className="bg-card p-8 rounded-2xl border border-red-500/20 flex flex-col space-y-6 max-w-sm w-full mx-4 shadow-2xl shadow-red-500/10 animate-in zoom-in-95 duration-300">
                        <div className="flex items-center space-x-4">
                            <div className="w-12 h-12 rounded-xl bg-red-500/10 border border-red-500/30 flex items-center justify-center shrink-0">
                                <svg className="w-6 h-6 text-red-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
                            </div>
                            <div>
                                <h3 className="text-sm font-black uppercase tracking-widest text-foreground">Remove {removeModal.handles.length} item{removeModal.handles.length > 1 ? 's' : ''}?</h3>
                                <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest mt-0.5">Choose what to remove</p>
                            </div>
                        </div>
                        {removeModal.names.length <= 5 && (
                            <ul className="space-y-1">
                                {removeModal.names.map((n, i) => (
                                    <li key={i} className="text-[11px] text-muted-foreground font-medium truncate">— {n}</li>
                                ))}
                            </ul>
                        )}
                        <div className="flex flex-col space-y-2 pt-1">
                            <button onClick={() => confirmRemove(true, true)} disabled={isRemoving} className="w-full px-4 py-2.5 bg-red-500 text-white rounded-md text-[10px] font-black uppercase tracking-widest hover:bg-red-600 active:scale-95 transition-all disabled:opacity-50">
                                {isRemoving ? 'Removing...' : 'Remove from Inventory & Storage'}
                            </button>
                            <button onClick={() => confirmRemove(true, false)} disabled={isRemoving} className="w-full px-4 py-2.5 bg-muted/40 text-foreground rounded-md text-[10px] font-black uppercase tracking-widest border border-border hover:bg-muted/60 active:scale-95 transition-all disabled:opacity-50">
                                Inventory only
                            </button>
                            <button onClick={() => confirmRemove(false, true)} disabled={isRemoving} className="w-full px-4 py-2.5 bg-muted/40 text-foreground rounded-md text-[10px] font-black uppercase tracking-widest border border-border hover:bg-muted/60 active:scale-95 transition-all disabled:opacity-50">
                                Storage only
                            </button>
                            <button onClick={() => setRemoveModal(null)} disabled={isRemoving} className="w-full px-4 py-2.5 bg-transparent text-muted-foreground rounded-md text-[10px] font-black uppercase tracking-widest hover:text-foreground transition-all">
                                Cancel
                            </button>
                        </div>
                    </div>
                </div>
            )}

            {/* Icon Popover */}
            {selectedIcon && (
                <div 
                    className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 backdrop-blur-sm animate-in fade-in duration-300"
                    onClick={() => setSelectedIcon(null)}
                >
                    <div className="card p-8 flex flex-col items-center space-y-6 max-w-sm w-full mx-4 shadow-2xl shadow-primary/20 border-primary/20 animate-in zoom-in-95 duration-300">
                        <div className="relative group">
                            <div className="absolute -inset-4 bg-primary/10 rounded-full blur-2xl group-hover:bg-primary/20 transition-all duration-500" />
                            <img 
                                src={selectedIcon.path} 
                                alt={selectedIcon.name}
                                className="w-48 h-48 object-contain relative z-10 drop-shadow-[0_0_15px_rgba(var(--primary),0.3)]"
                                onError={(e) => (e.currentTarget.src = '/src/assets/images/logo-universal.png')}
                            />
                        </div>
                        <div className="text-center space-y-2">
                            <h3 className="text-lg font-black uppercase tracking-widest text-foreground">{selectedIcon.name}</h3>
                            <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-[0.3em]">Item Preview</p>
                        </div>
                        <button className="text-[10px] font-black uppercase tracking-widest text-muted-foreground hover:text-foreground transition-colors">Click anywhere to close</button>
                    </div>
                </div>
            )}

            {/* Search Bar & Actions */}
            <div className="flex flex-col md:flex-row gap-4 shrink-0 items-center">
                <CategorySelect value={category} onChange={setCategory} className="w-full md:w-56" />

                {(Object.keys(editedInv).length > 0 || Object.keys(editedStorage).length > 0) && (
                    <button
                        onClick={saveChanges}
                        disabled={isSaving}
                        className="px-6 py-2.5 bg-primary text-primary-foreground rounded-md text-[10px] font-black uppercase tracking-widest shadow-lg shadow-primary/20 hover:scale-105 active:scale-95 transition-all disabled:opacity-50 disabled:scale-100"
                    >
                        {isSaving ? 'Saving...' : 'Save Changes'}
                    </button>
                )}
                {selectedKeys.size > 0 && (
                    <button
                        onClick={handleRemoveSelected}
                        className="px-6 py-2.5 bg-red-500/10 text-red-400 border border-red-500/30 rounded-md text-[10px] font-black uppercase tracking-widest hover:bg-red-500/20 active:scale-95 transition-all animate-in zoom-in-95 duration-200"
                    >
                        Remove ({selectedKeys.size})
                    </button>
                )}

                <div className="flex-1" />
                
                <div className="relative w-full max-w-xs">
                    <input 
                        type="text" 
                        placeholder="Search owned items..."
                        value={search}
                        onChange={e => setSearch(e.target.value)}
                        className="w-full bg-muted/30 border border-border rounded-md px-10 py-2.5 text-xs font-semibold focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition-all"
                    />
                    <div className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
                    </div>
                </div>
            </div>

            {/* Table Card */}
            <div className="card overflow-hidden flex flex-col flex-1 min-h-0">
                <div className="overflow-y-auto flex-1 custom-scrollbar">
                    <table className="w-full text-left text-sm border-collapse">
                        <thead className="bg-muted/30 text-[10px] font-black text-muted-foreground uppercase tracking-[0.2em] sticky top-0 z-10 backdrop-blur-md border-b border-border">
                            <tr>
                                <th className="px-4 py-4 w-10">
                                    <div
                                        onClick={toggleSelectAll}
                                        className={`w-4 h-4 rounded border flex items-center justify-center transition-all cursor-pointer ${selectedKeys.size === filteredOwnedItems.length && filteredOwnedItems.length > 0 ? 'bg-red-500 border-red-500' : 'bg-muted/30 border-border hover:border-red-400/50'}`}
                                    >
                                        {selectedKeys.size === filteredOwnedItems.length && filteredOwnedItems.length > 0 &&
                                            <svg className="w-3 h-3 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="4" d="M5 13l4 4L19 7"/></svg>}
                                    </div>
                                </th>
                                <th className="px-6 py-4 w-16">Icon</th>
                                <th className="px-6 py-4 cursor-pointer hover:text-primary transition-colors" onClick={() => handleSort('name')}>
                                    Name <SortIndicator col="name" />
                                </th>
                                {columnVisibility.id && (
                                    <th className="px-6 py-4 cursor-pointer hover:text-primary transition-colors" onClick={() => handleSort('id')}>
                                        ID <SortIndicator col="id" />
                                    </th>
                                )}
                                {columnVisibility.category && (
                                    <th className="px-6 py-4 cursor-pointer hover:text-primary transition-colors" onClick={() => handleSort('category')}>
                                        Category <SortIndicator col="category" />
                                    </th>
                                )}
                                <th className="px-6 py-4 text-center cursor-pointer hover:text-primary transition-colors" onClick={() => handleSort('currentUpgrade')}>
                                    Upgrade <SortIndicator col="currentUpgrade" />
                                </th>
                                <th className="px-6 py-4 text-center cursor-pointer hover:text-primary transition-colors" onClick={() => handleSort('maxUpgrade')}>
                                    Max Up <SortIndicator col="maxUpgrade" />
                                </th>
                                <th className="px-6 py-4 text-center w-32">Inventory</th>
                                <th className="px-6 py-4 text-center w-32">Storage</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-border/30">
                            {loading ? (
                                <tr>
                                    <td colSpan={9} className="px-6 py-24 text-center">
                                        <div className="flex flex-col items-center justify-center space-y-4">
                                            <div className="w-6 h-6 border-2 border-foreground/20 border-t-foreground rounded-full animate-spin" />
                                            <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest">Accessing data...</p>
                                        </div>
                                    </td>
                                </tr>
                            ) : filteredOwnedItems.length > 0 ? (
                                filteredOwnedItems.map((item) => {
                                    const key = rowKey(item);
                                    return (
                                    <tr key={key} className={`group hover:bg-primary/[0.02] transition-colors ${selectedKeys.has(key) ? 'bg-red-500/[0.03]' : ''}`}>
                                        <td className="px-4 py-0.5">
                                            <div
                                                onClick={() => toggleSelect(key)}
                                                className={`w-4 h-4 rounded border flex items-center justify-center transition-all cursor-pointer ${selectedKeys.has(key) ? 'bg-red-500 border-red-500' : 'bg-muted/30 border-border group-hover:border-red-400/50'}`}
                                            >
                                                {selectedKeys.has(key) &&
                                                    <svg className="w-3 h-3 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="4" d="M5 13l4 4L19 7"/></svg>}
                                            </div>
                                        </td>
                                        <td className="px-6 py-0.5">
                                            <div
                                                className="w-12 h-12 rounded bg-muted/30 border border-border/50 flex items-center justify-center overflow-hidden group-hover:border-primary/30 transition-all cursor-zoom-in"
                                                onClick={() => setSelectedIcon({name: item.name, path: item.iconPath})}
                                            >
                                                {brokenIcons.has(item.iconPath) ? (
                                                    <span className="text-[10px] font-black text-muted-foreground/30 select-none">?</span>
                                                ) : (
                                                    <img
                                                        src={item.iconPath}
                                                        alt=""
                                                        className="w-full h-full p-0.5 object-contain drop-shadow-md group-hover:scale-110 transition-transform duration-500"
                                                        onError={() => handleImageError(item.iconPath)}
                                                    />
                                                )}
                                            </div>
                                        </td>
                                        <td className="px-6 py-4">
                                            <div className="flex flex-col gap-0.5">
                                                <div className="flex items-center gap-1.5 flex-wrap">
                                                    <span className="text-[13px] font-semibold text-foreground group-hover:text-primary transition-colors">{item.name}</span>
                                                    {item.flags?.includes('cut_content') && (
                                                        <span className="text-[8px] font-black uppercase tracking-widest px-1.5 py-0.5 rounded bg-amber-500/15 text-amber-400 border border-amber-500/30">CUT</span>
                                                    )}
                                                    {item.flags?.includes('ban_risk') && (
                                                        <span className="text-[8px] font-black uppercase tracking-widest px-1.5 py-0.5 rounded bg-red-500/15 text-red-400 border border-red-500/30">⚠ BAN</span>
                                                    )}
                                                </div>
                                                <span className="text-[9px] font-bold text-muted-foreground/50 uppercase tracking-tighter">0x{item.id.toString(16).toUpperCase()}</span>
                                            </div>
                                        </td>
                                        {columnVisibility.id && (
                                            <td className="px-6 py-4 font-mono text-[10px] text-muted-foreground">0x{item.id.toString(16).toUpperCase()}</td>
                                        )}
                                        {columnVisibility.category && (
                                            <td className="px-6 py-4">
                                                <span className="text-[8px] font-black uppercase tracking-widest px-2 py-1 bg-muted/50 rounded border border-border/50 text-muted-foreground">
                                                    {item.subCategory === 'arrows_and_bolts' ? 'Arrows & Bolts' : item.subCategory.replace(/_/g, ' ')}
                                                </span>
                                            </td>
                                        )}
                                        <td className="px-6 py-4 text-center">
                                            <span className="text-[10px] font-black text-primary bg-primary/5 px-2 py-1 rounded border border-primary/10">
                                                {item.maxUpgrade > 0 ? `+${item.currentUpgrade}` : '—'}
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 text-center">
                                            <span className="text-[10px] font-black text-muted-foreground bg-muted/20 px-2 py-1 rounded border border-border/30">
                                                {item.maxUpgrade > 0 ? `+${item.maxUpgrade}` : '—'}
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 text-center">
                                            {item.nonStackable ? (
                                                <span className={`text-[10px] font-black uppercase tracking-widest px-2 py-1 rounded ${item.inInventory ? 'text-green-500 bg-green-500/10' : 'text-muted-foreground/30'}`}>
                                                    {item.inInventory ? '✓' : '—'}
                                                </span>
                                            ) : item.inInventory ? (
                                                <div className="flex items-center justify-center space-x-2">
                                                    <input
                                                        type="number"
                                                        min={0}
                                                        max={item.maxInv}
                                                        value={editedInv[item.invHandle] !== undefined ? editedInv[item.invHandle] : item.invQty}
                                                        onChange={e => handleQtyChange(item.invHandle, e.target.value, 'inv', item.maxInv)}
                                                        className={`w-16 bg-muted/20 border rounded px-2 py-1 text-center text-xs font-bold outline-none focus:ring-1 focus:ring-primary/30 transition-all ${editedInv[item.invHandle] !== undefined ? 'border-primary/50 text-primary bg-primary/5' : 'border-border/50 text-foreground'}`}
                                                    />
                                                    <span className="text-[9px] font-bold text-muted-foreground/30 uppercase tracking-tighter">/ {item.maxInv}</span>
                                                </div>
                                            ) : (
                                                <span className="text-muted-foreground/30 text-[10px] font-black">—</span>
                                            )}
                                        </td>
                                        <td className="px-6 py-4 text-center">
                                            {item.nonStackable ? (
                                                <span className={`text-[10px] font-black uppercase tracking-widest px-2 py-1 rounded ${item.inStorage ? 'text-green-500 bg-green-500/10' : 'text-muted-foreground/30'}`}>
                                                    {item.inStorage ? '✓' : '—'}
                                                </span>
                                            ) : item.inStorage ? (
                                                <div className="flex items-center justify-center space-x-2">
                                                    <input
                                                        type="number"
                                                        min={0}
                                                        max={item.maxStorage}
                                                        value={editedStorage[item.storageHandle] !== undefined ? editedStorage[item.storageHandle] : item.storageQty}
                                                        onChange={e => handleQtyChange(item.storageHandle, e.target.value, 'storage', item.maxStorage)}
                                                        className={`w-16 bg-muted/20 border rounded px-2 py-1 text-center text-xs font-bold outline-none focus:ring-1 focus:ring-primary/30 transition-all ${editedStorage[item.storageHandle] !== undefined ? 'border-primary/50 text-primary bg-primary/5' : 'border-border/50 text-foreground'}`}
                                                    />
                                                    <span className="text-[9px] font-bold text-muted-foreground/30 uppercase tracking-tighter">/ {item.maxStorage}</span>
                                                </div>
                                            ) : (
                                                <span className="text-muted-foreground/30 text-[10px] font-black">—</span>
                                            )}
                                        </td>
                                    </tr>
                                    );})
                            ) : (
                                <tr>
                                    <td colSpan={9} className="px-6 py-24 text-center">
                                        <p className="text-xs text-muted-foreground font-medium italic">Nothing found in this section.</p>
                                    </td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
}
