import {useEffect, useState} from 'react';
import {GetCharacter} from '../../wailsjs/go/main/App';
import {vm} from '../../wailsjs/go/models';

interface InventoryTabProps {
    charIndex: number;
    inventoryVersion: number;
    columnVisibility: {
        id: boolean;
        category: boolean;
    };
}

export function InventoryTab({ charIndex, inventoryVersion, columnVisibility }: InventoryTabProps) {
    const [category, setCategory] = useState('all');
    const [search, setSearch] = useState('');
    const [charInventory, setCharInventory] = useState<vm.ItemViewModel[]>([]);
    const [charStorage, setCharStorage] = useState<vm.ItemViewModel[]>([]);
    const [loading, setLoading] = useState(false);
    
    // Sorting state
    const [sortCol, setSortCol] = useState<string>('name');
    const [sortDir, setSortDir] = useState<'asc' | 'desc'>('asc');

    const [selectedIcon, setSelectedIcon] = useState<{name: string, path: string} | null>(null);
    const [isSaving, setIsSaving] = useState(false);

    // Local state for edited quantities
    const [editedInv, setEditedInv] = useState<Record<number, number>>({});
    const [editedStorage, setEditedStorage] = useState<Record<number, number>>({});

    const handleQtyChange = (handle: number, value: string, type: 'inv' | 'storage', max: number) => {
        const qty = parseInt(value) || 0;
        const safeQty = Math.min(Math.max(0, qty), max);
        
        if (type === 'inv') {
            setEditedInv(prev => ({ ...prev, [handle]: safeQty }));
        } else {
            setEditedStorage(prev => ({ ...prev, [handle]: safeQty }));
        }
    };

    const saveChanges = async () => {
        if (isSaving) return;
        setIsSaving(true);
        try {
            const char = await GetCharacter(charIndex);
            if (!char) return;

            // Apply local edits to the character VM
            char.inventory = char.inventory.map(item => ({
                ...item,
                quantity: editedInv[item.handle] !== undefined ? editedInv[item.handle] : item.quantity
            }));
            char.storage = char.storage.map(item => ({
                ...item,
                quantity: editedStorage[item.handle] !== undefined ? editedStorage[item.handle] : item.quantity
            }));

            // @ts-ignore - SaveCharacter is generated by Wails
            await window.go.main.App.SaveCharacter(charIndex, char);
            
            // Refresh data
            const updatedChar = await GetCharacter(charIndex);
            setCharInventory(updatedChar?.inventory || []);
            setCharStorage(updatedChar?.storage || []);
            setEditedInv({});
            setEditedStorage({});
            
        } catch (err) {
            console.error("Failed to save inventory changes:", err);
        } finally {
            setIsSaving(false);
        }
    };

    type MergedItem = {
        id: number; handle: number; name: string; category: string; subCategory: string;
        nonStackable: boolean; inInventory: boolean; inStorage: boolean;
        invQty: number; storageQty: number;
        maxInv: number; maxStorage: number; maxUpgrade: number; currentUpgrade: number; iconPath: string;
    };

    // Merge inventory and storage items for display.
    // Non-stackable (maxInventory <= 1): one row per handle — each copy shown separately.
    // Stackable (maxInventory > 1): one row per id — qty merged from both locations.
    const mergedOwnedItems = (() => {
        const rows: MergedItem[] = [];
        const stackableMap = new Map<number, MergedItem>();

        charInventory.forEach(item => {
            if (item.maxInventory <= 1) {
                rows.push({
                    id: item.id, handle: item.handle, name: item.name,
                    category: item.category, subCategory: item.subCategory,
                    nonStackable: true, inInventory: true, inStorage: false,
                    invQty: 1, storageQty: 0,
                    maxInv: item.maxInventory, maxStorage: item.maxStorage,
                    maxUpgrade: item.maxUpgrade, currentUpgrade: item.currentUpgrade ?? 0, iconPath: item.iconPath,
                });
            } else {
                stackableMap.set(item.id, {
                    id: item.id, handle: item.handle, name: item.name,
                    category: item.category, subCategory: item.subCategory,
                    nonStackable: false, inInventory: true, inStorage: false,
                    invQty: item.quantity, storageQty: 0,
                    maxInv: item.maxInventory, maxStorage: item.maxStorage,
                    maxUpgrade: item.maxUpgrade, currentUpgrade: item.currentUpgrade ?? 0, iconPath: item.iconPath,
                });
            }
        });

        charStorage.forEach(item => {
            if (item.maxInventory <= 1) {
                rows.push({
                    id: item.id, handle: item.handle, name: item.name,
                    category: item.category, subCategory: item.subCategory,
                    nonStackable: true, inInventory: false, inStorage: true,
                    invQty: 0, storageQty: 1,
                    maxInv: item.maxInventory, maxStorage: item.maxStorage,
                    maxUpgrade: item.maxUpgrade, currentUpgrade: item.currentUpgrade ?? 0, iconPath: item.iconPath,
                });
            } else {
                const existing = stackableMap.get(item.id);
                if (existing) {
                    existing.inStorage = true;
                    existing.storageQty = item.quantity;
                } else {
                    stackableMap.set(item.id, {
                        id: item.id, handle: item.handle, name: item.name,
                        category: item.category, subCategory: item.subCategory,
                        nonStackable: false, inInventory: false, inStorage: true,
                        invQty: 0, storageQty: item.quantity,
                        maxInv: item.maxInventory, maxStorage: item.maxStorage,
                        maxUpgrade: item.maxUpgrade, currentUpgrade: item.currentUpgrade ?? 0, iconPath: item.iconPath,
                    });
                }
            }
        });

        return [...rows, ...Array.from(stackableMap.values())];
    })();

    const handleImageError = (e: React.SyntheticEvent<HTMLImageElement, Event>) => {
        const target = e.currentTarget;
        target.style.display = 'none';
        const parent = target.parentElement;
        if (parent) {
            const placeholder = document.createElement('div');
            placeholder.className = 'text-[10px] font-black text-muted-foreground/30 select-none';
            placeholder.innerText = '?';
            parent.appendChild(placeholder);
        }
    };

    useEffect(() => {
        setLoading(true);
        GetCharacter(charIndex).then(res => {
            setCharInventory(res?.inventory || []);
            setCharStorage(res?.storage || []);
        }).finally(() => setLoading(false));
    }, [charIndex, inventoryVersion]);

    const handleSort = (col: string) => {
        if (sortCol === col) {
            setSortDir(sortDir === 'asc' ? 'desc' : 'asc');
        } else {
            setSortCol(col);
            setSortDir('asc');
        }
    };

    const sortItems = (items: any[]) => {
        return [...items].sort((a, b) => {
            let valA = a[sortCol as keyof typeof a];
            let valB = b[sortCol as keyof typeof b];

            if (sortCol === 'maxUpgrade') {
                valA = a.maxUpgrade || 0;
                valB = b.maxUpgrade || 0;
            } else if (sortCol === 'currentUpgrade') {
                valA = a.currentUpgrade || 0;
                valB = b.currentUpgrade || 0;
            } else if (typeof valA === 'string') {
                valA = valA.toLowerCase();
                valB = valB.toLowerCase();
            }

            if (valA < valB) return sortDir === 'asc' ? -1 : 1;
            if (valA > valB) return sortDir === 'asc' ? 1 : -1;
            return 0;
        });
    };

    const filteredOwnedItems = sortItems(mergedOwnedItems.filter(item => {
        const matchesSearch = item.name.toLowerCase().includes(search.toLowerCase()) || 
                            item.id.toString(16).toLowerCase().includes(search.toLowerCase());
        
        if (category === 'all') return matchesSearch;
        
        return item.subCategory === category && matchesSearch;
    }));

    const SortIndicator = ({ col }: { col: string }) => {
        if (sortCol !== col) return <span className="ml-1 opacity-20">↕</span>;
        return <span className="ml-1 text-primary">{sortDir === 'asc' ? '↑' : '↓'}</span>;
    };

    return (
        <div className="flex-1 flex flex-col min-h-0 space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-700">
            {/* Icon Popover */}
            {selectedIcon && (
                <div 
                    className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 backdrop-blur-sm animate-in fade-in duration-300"
                    onClick={() => setSelectedIcon(null)}
                >
                    <div className="card p-8 flex flex-col items-center space-y-6 max-w-sm w-full mx-4 shadow-2xl shadow-primary/20 border-primary/20 animate-in zoom-in-95 duration-300">
                        <div className="relative group">
                            <div className="absolute -inset-4 bg-primary/10 rounded-full blur-2xl group-hover:bg-primary/20 transition-all duration-500" />
                            <img 
                                src={selectedIcon.path} 
                                alt={selectedIcon.name}
                                className="w-48 h-48 object-contain relative z-10 drop-shadow-[0_0_15px_rgba(var(--primary),0.3)]"
                                onError={(e) => (e.currentTarget.src = '/src/assets/images/logo-universal.png')}
                            />
                        </div>
                        <div className="text-center space-y-2">
                            <h3 className="text-lg font-black uppercase tracking-widest text-foreground">{selectedIcon.name}</h3>
                            <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-[0.3em]">Item Preview</p>
                        </div>
                        <button className="text-[10px] font-black uppercase tracking-widest text-muted-foreground hover:text-foreground transition-colors">Click anywhere to close</button>
                    </div>
                </div>
            )}

            {/* Search Bar & Actions */}
            <div className="flex flex-col md:flex-row gap-4 shrink-0 items-center">
                <div className="relative w-full md:w-56">
                    <select 
                        value={category}
                        onChange={e => setCategory(e.target.value)}
                        className="w-full appearance-none bg-muted/30 border border-border rounded-md px-4 py-2.5 pr-10 text-[10px] font-black uppercase tracking-widest text-muted-foreground outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition-all cursor-pointer"
                    >
                        <option value="all">All Categories</option>
                        <optgroup label="Equipment" className="bg-background text-foreground">
                            <option value="weapons">Melee Weapons</option>
                            <option value="bows">Bows & Ballistae</option>
                            <option value="arrows_and_bolts">Arrows & Bolts</option>
                            <option value="shields">Shields</option>
                            <option value="staffs">Glintstone Staffs</option>
                            <option value="seals">Sacred Seals</option>
                            <option value="talismans">Talismans</option>
                            <option value="aows">Ashes of War</option>
                        </optgroup>
                        <optgroup label="Armor" className="bg-background text-foreground">
                            <option value="helms">Helms</option>
                            <option value="chest">Chest Armor</option>
                            <option value="gauntlets">Gauntlets</option>
                            <option value="leggings">Leggings</option>
                        </optgroup>
                        <optgroup label="Magic & Ashes" className="bg-background text-foreground">
                            <option value="sorceries">Sorceries</option>
                            <option value="incantations">Incantations</option>
                            <option value="ashes">Spirit Ashes</option>
                        </optgroup>
                        <optgroup label="Items & Materials" className="bg-background text-foreground">
                            <option value="crafting_materials">Crafting Materials</option>
                            <option value="bolstering_materials">Bolstering Materials</option>
                            <option value="consumables">Consumables</option>
                        </optgroup>
                        <optgroup label="Tools" className="bg-background text-foreground">
                            <option value="sacred_flasks">Sacred Flasks</option>
                            <option value="throwing_pots">Throwing Pots</option>
                            <option value="perfume_arts">Perfume Arts</option>
                            <option value="throwables">Throwables</option>
                            <option value="grease">Grease</option>
                            <option value="misc_tools">Miscellaneous Tools</option>
                            <option value="quest_tools">Quest Tools</option>
                            <option value="golden_runes">Golden Runes</option>
                            <option value="remembrances">Remembrances</option>
                            <option value="multiplayer">Multiplayer Items</option>
                        </optgroup>
                        <optgroup label="Progress" className="bg-background text-foreground">
                            <option value="keyitems">Key Items</option>
                        </optgroup>
                    </select>
                    <div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none text-muted-foreground">
                        <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M19 9l-7 7-7-7"></path></svg>
                    </div>
                </div>

                {(Object.keys(editedInv).length > 0 || Object.keys(editedStorage).length > 0) && (
                    <button 
                        onClick={saveChanges}
                        disabled={isSaving}
                        className="px-6 py-2.5 bg-primary text-primary-foreground rounded-md text-[10px] font-black uppercase tracking-widest shadow-lg shadow-primary/20 hover:scale-105 active:scale-95 transition-all disabled:opacity-50 disabled:scale-100"
                    >
                        {isSaving ? 'Saving...' : 'Save Changes'}
                    </button>
                )}

                <div className="flex-1" />
                
                <div className="relative w-full max-w-xs">
                    <input 
                        type="text" 
                        placeholder="Search owned items..."
                        value={search}
                        onChange={e => setSearch(e.target.value)}
                        className="w-full bg-muted/30 border border-border rounded-md px-10 py-2.5 text-xs font-semibold focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition-all"
                    />
                    <div className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
                    </div>
                </div>
            </div>

            {/* Table Card */}
            <div className="card overflow-hidden flex flex-col flex-1 min-h-0">
                <div className="overflow-y-auto flex-1 custom-scrollbar">
                    <table className="w-full text-left text-sm border-collapse">
                        <thead className="bg-muted/30 text-[10px] font-black text-muted-foreground uppercase tracking-[0.2em] sticky top-0 z-10 backdrop-blur-md border-b border-border">
                            <tr>
                                <th className="px-6 py-4 w-16">Icon</th>
                                <th className="px-6 py-4 cursor-pointer hover:text-primary transition-colors" onClick={() => handleSort('name')}>
                                    Name <SortIndicator col="name" />
                                </th>
                                {columnVisibility.id && (
                                    <th className="px-6 py-4 cursor-pointer hover:text-primary transition-colors" onClick={() => handleSort('id')}>
                                        ID <SortIndicator col="id" />
                                    </th>
                                )}
                                {columnVisibility.category && (
                                    <th className="px-6 py-4 cursor-pointer hover:text-primary transition-colors" onClick={() => handleSort('category')}>
                                        Category <SortIndicator col="category" />
                                    </th>
                                )}
                                <th className="px-6 py-4 text-center cursor-pointer hover:text-primary transition-colors" onClick={() => handleSort('currentUpgrade')}>
                                    Upgrade <SortIndicator col="currentUpgrade" />
                                </th>
                                <th className="px-6 py-4 text-center cursor-pointer hover:text-primary transition-colors" onClick={() => handleSort('maxUpgrade')}>
                                    Max Up <SortIndicator col="maxUpgrade" />
                                </th>
                                <th className="px-6 py-4 text-center w-32">Inventory</th>
                                <th className="px-6 py-4 text-center w-32">Storage</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-border/30">
                            {loading ? (
                                <tr>
                                    <td colSpan={8} className="px-6 py-24 text-center">
                                        <div className="flex flex-col items-center justify-center space-y-4">
                                            <div className="w-6 h-6 border-2 border-foreground/20 border-t-foreground rounded-full animate-spin" />
                                            <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest">Accessing data...</p>
                                        </div>
                                    </td>
                                </tr>
                            ) : filteredOwnedItems.length > 0 ? (
                                filteredOwnedItems.map((item) => (
                                    <tr key={item.handle} className="group hover:bg-primary/[0.02] transition-colors">
                                        <td className="px-6 py-0.5">
                                            <div 
                                                className="w-12 h-12 rounded bg-muted/30 border border-border/50 flex items-center justify-center overflow-hidden group-hover:border-primary/30 transition-all cursor-zoom-in"
                                                onClick={() => setSelectedIcon({name: item.name, path: item.iconPath})}
                                            >
                                                <img 
                                                    src={item.iconPath} 
                                                    alt="" 
                                                    className="w-full h-full p-0.5 object-contain drop-shadow-md group-hover:scale-110 transition-transform duration-500"
                                                    onError={handleImageError}
                                                />
                                            </div>
                                        </td>
                                        <td className="px-6 py-4">
                                            <div className="flex flex-col">
                                                <span className="font-black uppercase tracking-widest text-foreground group-hover:text-primary transition-colors">{item.name}</span>
                                                <span className="text-[9px] font-bold text-muted-foreground/50 uppercase tracking-tighter">0x{item.id.toString(16).toUpperCase()}</span>
                                            </div>
                                        </td>
                                        {columnVisibility.id && (
                                            <td className="px-6 py-4 font-mono text-[10px] text-muted-foreground">0x{item.id.toString(16).toUpperCase()}</td>
                                        )}
                                        {columnVisibility.category && (
                                            <td className="px-6 py-4">
                                                <span className="text-[8px] font-black uppercase tracking-widest px-2 py-1 bg-muted/50 rounded border border-border/50 text-muted-foreground">
                                                    {item.subCategory.replace('_', ' ')}
                                                </span>
                                            </td>
                                        )}
                                        <td className="px-6 py-4 text-center">
                                            <span className="text-[10px] font-black text-primary bg-primary/5 px-2 py-1 rounded border border-primary/10">
                                                {item.maxUpgrade > 0 ? `+${item.currentUpgrade}` : '—'}
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 text-center">
                                            <span className="text-[10px] font-black text-muted-foreground bg-muted/20 px-2 py-1 rounded border border-border/30">
                                                {item.maxUpgrade > 0 ? `+${item.maxUpgrade}` : '—'}
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 text-center">
                                            {item.nonStackable ? (
                                                <span className={`text-[10px] font-black uppercase tracking-widest px-2 py-1 rounded ${item.inInventory ? 'text-green-500 bg-green-500/10' : 'text-muted-foreground/30'}`}>
                                                    {item.inInventory ? '✓' : '—'}
                                                </span>
                                            ) : (
                                                <div className="flex items-center justify-center space-x-2">
                                                    <input
                                                        type="number"
                                                        value={editedInv[item.handle] !== undefined ? editedInv[item.handle] : item.invQty}
                                                        onChange={e => handleQtyChange(item.handle, e.target.value, 'inv', item.maxInv)}
                                                        className={`w-16 bg-muted/20 border rounded px-2 py-1 text-center text-xs font-bold outline-none focus:ring-1 focus:ring-primary/30 transition-all ${editedInv[item.handle] !== undefined ? 'border-primary/50 text-primary bg-primary/5' : 'border-border/50 text-foreground'}`}
                                                    />
                                                    <span className="text-[9px] font-bold text-muted-foreground/30 uppercase tracking-tighter">/ {item.maxInv}</span>
                                                </div>
                                            )}
                                        </td>
                                        <td className="px-6 py-4 text-center">
                                            {item.nonStackable ? (
                                                <span className={`text-[10px] font-black uppercase tracking-widest px-2 py-1 rounded ${item.inStorage ? 'text-green-500 bg-green-500/10' : 'text-muted-foreground/30'}`}>
                                                    {item.inStorage ? '✓' : '—'}
                                                </span>
                                            ) : (
                                                <div className="flex items-center justify-center space-x-2">
                                                    <input
                                                        type="number"
                                                        value={editedStorage[item.handle] !== undefined ? editedStorage[item.handle] : item.storageQty}
                                                        onChange={e => handleQtyChange(item.handle, e.target.value, 'storage', item.maxStorage)}
                                                        className={`w-16 bg-muted/20 border rounded px-2 py-1 text-center text-xs font-bold outline-none focus:ring-1 focus:ring-primary/30 transition-all ${editedStorage[item.handle] !== undefined ? 'border-primary/50 text-primary bg-primary/5' : 'border-border/50 text-foreground'}`}
                                                    />
                                                    <span className="text-[9px] font-bold text-muted-foreground/30 uppercase tracking-tighter">/ {item.maxStorage}</span>
                                                </div>
                                            )}
                                        </td>
                                    </tr>
                                ))
                            ) : (
                                <tr>
                                    <td colSpan={8} className="px-6 py-24 text-center">
                                        <p className="text-xs text-muted-foreground font-medium italic">Nothing found in this section.</p>
                                    </td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
}
