// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetCharacterDetails(arg1:number):Promise<backend.CharacterDetails>;

export function GetCharacters():Promise<Array<backend.CharacterInfo>>;

export function Greet(arg1:string):Promise<string>;

export function OpenSaveFile():Promise<string>;

export function SaveCharacterDetails(arg1:backend.CharacterDetails):Promise<void>;
