// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCharacterDetails(arg1) {
  return window['go']['backend']['App']['GetCharacterDetails'](arg1);
}

export function GetCharacters() {
  return window['go']['backend']['App']['GetCharacters']();
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function OpenSaveFile() {
  return window['go']['backend']['App']['OpenSaveFile']();
}

export function SaveCharacterDetails(arg1) {
  return window['go']['backend']['App']['SaveCharacterDetails'](arg1);
}
