// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBosses(arg1) {
  return window['go']['backend']['App']['GetBosses'](arg1);
}

export function GetCharacterDetails(arg1) {
  return window['go']['backend']['App']['GetCharacterDetails'](arg1);
}

export function GetCharacters() {
  return window['go']['backend']['App']['GetCharacters']();
}

export function GetGraces(arg1) {
  return window['go']['backend']['App']['GetGraces'](arg1);
}

export function GetSteamID() {
  return window['go']['backend']['App']['GetSteamID']();
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function OpenSaveFile() {
  return window['go']['backend']['App']['OpenSaveFile']();
}

export function SaveCharacterDetails(arg1) {
  return window['go']['backend']['App']['SaveCharacterDetails'](arg1);
}

export function SaveSteamID(arg1) {
  return window['go']['backend']['App']['SaveSteamID'](arg1);
}

export function SetEventFlag(arg1, arg2, arg3) {
  return window['go']['backend']['App']['SetEventFlag'](arg1, arg2, arg3);
}
