// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddBulkItems(arg1:number,arg2:string):Promise<number>;

export function GetBosses(arg1:number):Promise<Array<backend.EventItem>>;

export function GetCharacterDetails(arg1:number):Promise<backend.CharacterDetails>;

export function GetCharacters():Promise<Array<backend.CharacterInfo>>;

export function GetGraces(arg1:number):Promise<Array<backend.EventItem>>;

export function GetSteamID():Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function OpenSaveFile():Promise<string>;

export function SaveCharacterDetails(arg1:backend.CharacterDetails):Promise<void>;

export function SaveSteamID(arg1:number):Promise<void>;

export function SetEventFlag(arg1:number,arg2:number,arg3:boolean):Promise<void>;
