package diagnostics

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"regexp"
	"strconv"
	"sync"
	"time"

	"github.com/oisis/EldenRing-SaveForge/backend/apperror"
	"github.com/oisis/EldenRing-SaveForge/backend/deployment"
)

// bufferCapacity is the fixed number of newest records the console can read.
const bufferCapacity = 500

// queueCapacity bounds the hand-off to the file writer. Log never blocks on a
// full queue: a slow or stuck disk must not be able to hold up a save, an edit
// or a deployment, so the record is dropped and counted instead.
const queueCapacity = 256

// allowedStages is the closed stage vocabulary. It is exactly the stage
// catalogue deployment already publishes, read from that package rather than
// copied, so the two cannot drift apart.
var allowedStages = map[string]bool{
	deployment.StageGameStatus: true,
	deployment.StageStopGame:   true,
	deployment.StageStabilise:  true,
	deployment.StageBackup:     true,
	deployment.StageTransfer:   true,
	deployment.StageReplace:    true,
	deployment.StageVerify:     true,
	deployment.StageLaunchGame: true,
	deployment.StageDownload:   true,
	deployment.StageRetention:  true,
}

// allowedTargetStates is the real target state an operation reported, taken
// from deployment's own closed vocabulary.
var allowedTargetStates = map[string]bool{
	deployment.TargetStateUnchanged:               true,
	deployment.TargetStateReplacedVerified:        true,
	deployment.TargetStateReplacedUnverified:      true,
	deployment.TargetStateReplacementUndetermined: true,
}

// allowedCodes is the closed set of reason codes a record may carry: the
// application error codes and the deployment block and failure codes. An
// error's own text, its cause and its stack are never candidates.
var allowedCodes = map[string]bool{
	apperror.CodeInvalidRequest:                true,
	apperror.CodeInvalidRevision:               true,
	apperror.CodeRevisionConflict:              true,
	apperror.CodeUnknownSaveSession:            true,
	apperror.CodeOperationFailed:               true,
	apperror.CodeInternalError:                 true,
	deployment.BlockedGameRunning:              true,
	deployment.BlockedGameStatusUnknown:        true,
	deployment.BlockedRemoteBackupConfirmation: true,
	deployment.BlockedStopGameConfirmation:     true,
	deployment.BlockedCancelled:                true,
	deployment.FailureReplacement:              true,
	deployment.FailureVerification:             true,
	deployment.FailureLaunch:                   true,
	deployment.FailureMetadata:                 true,
	deployment.FailureReplacementUndetermined:  true,
}

// Entry is the only way to produce a record. Every member is a closed
// identifier, a generated correlation value or a number; there is deliberately
// no free-text field and no map[string]any, so a caller cannot smuggle a path,
// a host, an account name or a raw error into the diagnostics at all.
type Entry struct {
	Event string
	// Operation and Stage name a shared boundary, never an endpoint.
	Operation string
	Stage     string
	// Status is required by EventOperationFinished and unused elsewhere.
	Status string
	// CorrelationID ties one operation's records together. It is generated by
	// the caller for exactly one execution and carries no user data.
	CorrelationID string
	// Code is one closed reason code: an application error code or a deployment
	// block or failure code.
	Code string
	// TargetState is the real deployment target state, from deployment's own
	// vocabulary.
	TargetState string
	// DurationMS and Count are plain numbers: elapsed time and a cardinality
	// such as a stage or record count.
	DurationMS int64
	Count      int
	// Enabled is carried by EventDiagnosticModeChanged only.
	Enabled bool
	// Version, Build and Platform are carried by EventApplicationStarted only. They are
	// build facts, never host facts: no host name, user or path is involved.
	Version  string
	Build    string
	Platform string
}

// Record is one safe, structured diagnostic entry as the console, the local
// file and the exported report all read it. The three share this one shape;
// none of them has an emitter or a redaction rule of its own.
type Record struct {
	Seq           uint64 `json:"seq"`
	Timestamp     string `json:"timestamp"`
	Severity      string `json:"severity"`
	Event         string `json:"event"`
	Message       string `json:"message"`
	Operation     string `json:"operation,omitempty"`
	Stage         string `json:"stage,omitempty"`
	Status        string `json:"status,omitempty"`
	CorrelationID string `json:"correlationID,omitempty"`
	Code          string `json:"code,omitempty"`
	TargetState   string `json:"targetState,omitempty"`
	DurationMS    int64  `json:"durationMS,omitempty"`
	Count         int    `json:"count,omitempty"`
	Enabled       *bool  `json:"enabled,omitempty"`
	Version       string `json:"version,omitempty"`
	Build         string `json:"build,omitempty"`
	Platform      string `json:"platform,omitempty"`
}

// Page is a cursor-addressed portion of the global record buffer. The cursor
// semantics match the session journal: it is the sequence number of the last
// record already seen, so an incremental poll never repeats an entry.
type Page struct {
	Records               []Record `json:"records"`
	NextCursor            string   `json:"nextCursor"`
	HasMore               bool     `json:"hasMore"`
	TotalBuffered         int      `json:"totalBuffered"`
	CursorExpired         bool     `json:"cursorExpired"`
	OldestAvailableCursor string   `json:"oldestAvailableCursor"`
}

// State is what the Settings screen and the exported report read about the
// diagnostics themselves.
type State struct {
	Enabled bool `json:"enabled"`
	// LogDirectoryExists states whether this host has a local log directory to
	// open at all. A build without a state directory reports false truthfully.
	LogDirectoryExists bool `json:"logDirectoryExists"`
	// LocalLoggingAvailable is false once the sink failed. The application keeps
	// running and the in-memory buffer keeps working; only the file is gone.
	LocalLoggingAvailable bool `json:"localLoggingAvailable"`
	// DroppedRecords counts what never reached the file: rejected entries, a
	// full queue and oversized records. It is reported rather than logged, so a
	// failing logger never logs about itself.
	DroppedRecords int `json:"droppedRecords"`
}

// Options configures one Service. An empty Directory selects the in-memory
// mode: the buffer works, nothing is written and LogDirectoryExists is false.
type Options struct {
	Directory string
	// Now is the clock. A nil value selects time.Now; only a test replaces it.
	Now func() time.Time
}

// Service is the single owner of the diagnostic mode, the record buffer and
// the local sink.
type Service struct {
	mutex   sync.Mutex
	enabled bool
	seq     uint64
	buffer  []Record
	dropped int
	closed  bool

	now       func() time.Time
	directory string

	queue    chan Record
	done     chan struct{}
	closeOne sync.Once
	// sinkFailed is set by the writer goroutine and read under mutex, so the
	// Settings screen can state "local diagnostics are unavailable" instead of
	// pretending the file is being written.
	sinkFailed bool
}

// NewService returns a service and, when a directory is configured, starts the
// single writer goroutine that owns the local file.
func NewService(options Options) *Service {
	service := &Service{
		now:       options.Now,
		directory: options.Directory,
	}
	if service.now == nil {
		service.now = time.Now
	}
	if options.Directory != "" {
		// Initialisation runs in the composition root, never under an engine lock.
		service.sinkFailed = os.MkdirAll(options.Directory, 0o700) != nil
		service.queue = make(chan Record, queueCapacity)
		service.done = make(chan struct{})
		go service.writeLoop()
	}
	return service
}

// SetDebugMode turns extended diagnostics on or off for this instance and
// reports the state now in effect. It is runtime state only: no save session,
// revision, history entry or recovery journal is involved, and nothing is
// persisted for the next launch.
func (service *Service) SetDebugMode(enabled bool) State {
	if service == nil {
		return State{}
	}
	service.mutex.Lock()
	changed := service.enabled != enabled
	service.enabled = enabled
	service.mutex.Unlock()
	if changed {
		// The change itself is an info record, so disabling the mode is still
		// visible in the log it stopped extending.
		service.Log(Entry{Event: EventDiagnosticModeChanged, Enabled: enabled})
	}
	return service.State()
}

// State reports the current diagnostic state.
func (service *Service) State() State {
	if service == nil {
		return State{}
	}
	info, err := os.Stat(service.directory)
	exists := err == nil && info.IsDir()
	service.mutex.Lock()
	defer service.mutex.Unlock()
	return State{
		Enabled:               service.enabled,
		LogDirectoryExists:    exists,
		LocalLoggingAvailable: exists && !service.sinkFailed,
		DroppedRecords:        service.dropped,
	}
}

// Directory reports the local log directory, or an empty string for a host
// that has none. It is the location the Settings screen offers to open; the
// frontend never supplies or receives a path of its own.
func (service *Service) Directory() string {
	if service == nil {
		return ""
	}
	if !service.State().LogDirectoryExists {
		return ""
	}
	return service.directory
}

// Log records one entry. An entry naming anything outside the closed catalogue
// is rejected rather than recorded, and a debug entry is dropped while Debug
// Mode is off. Nothing here blocks: the buffer append is a short critical
// section of its own and the file write is handed to the writer goroutine.
func (service *Service) Log(entry Entry) {
	if service == nil {
		return
	}
	service.build(entry)
}

var correlationPattern = regexp.MustCompile(`^[0-9a-f]{16}$`)
var versionPattern = regexp.MustCompile(`^[vV]?[0-9]+\.[0-9]+\.[0-9]+(?:[-+][a-zA-Z0-9.-]+)?$`)
var buildPattern = regexp.MustCompile(`^(?:development|[0-9a-f]{7,64})$`)
var platformPattern = regexp.MustCompile(`^(?:darwin|windows|linux)/(?:amd64|arm64)$`)

// build validates one entry and appends the resulting record to the buffer. It
// reports false when nothing was recorded.
func (service *Service) build(entry Entry) (Record, bool) {
	if (entry.CorrelationID != "" && !correlationPattern.MatchString(entry.CorrelationID)) ||
		(entry.Version != "" && entry.Version != "dev" && (len(entry.Version) > 64 || !versionPattern.MatchString(entry.Version))) ||
		(entry.Build != "" && (len(entry.Build) > 64 || (!buildPattern.MatchString(entry.Build) && !versionPattern.MatchString(entry.Build)))) ||
		(entry.Platform != "" && !platformPattern.MatchString(entry.Platform)) ||
		entry.DurationMS < 0 || entry.Count < 0 {
		return Record{}, service.reject()
	}
	message, known := eventMessages[entry.Event]
	if !known {
		return Record{}, service.reject()
	}
	severity, known := severityFor(entry)
	if !known || !allowedSeverities[severity] {
		return Record{}, service.reject()
	}
	if entry.Operation != "" && !allowedOperations[entry.Operation] {
		return Record{}, service.reject()
	}
	if entry.Stage != "" && !allowedStages[entry.Stage] {
		return Record{}, service.reject()
	}
	if entry.Status != "" && !allowedStatuses[entry.Status] {
		return Record{}, service.reject()
	}
	if entry.Code != "" && !allowedCodes[entry.Code] {
		return Record{}, service.reject()
	}
	if entry.TargetState != "" && !allowedTargetStates[entry.TargetState] {
		return Record{}, service.reject()
	}

	service.mutex.Lock()
	defer service.mutex.Unlock()
	if service.closed {
		return Record{}, false
	}
	if severity == SeverityDebug && !service.enabled {
		return Record{}, false
	}
	service.seq++
	record := Record{
		Seq:           service.seq,
		Timestamp:     service.now().UTC().Format(time.RFC3339),
		Severity:      severity,
		Event:         entry.Event,
		Message:       message,
		Operation:     entry.Operation,
		Stage:         entry.Stage,
		Status:        entry.Status,
		CorrelationID: entry.CorrelationID,
		Code:          entry.Code,
		TargetState:   entry.TargetState,
		DurationMS:    entry.DurationMS,
		Count:         entry.Count,
		Version:       entry.Version,
		Build:         entry.Build,
		Platform:      entry.Platform,
	}
	if entry.Event == EventDiagnosticModeChanged {
		enabled := entry.Enabled
		record.Enabled = &enabled
	}
	if len(service.buffer) < bufferCapacity {
		service.buffer = append(service.buffer, record)
	} else {
		copy(service.buffer, service.buffer[1:])
		service.buffer[bufferCapacity-1] = record
	}
	// The buffer and queue share the same lock and ordering, including Close.
	if service.queue != nil {
		select {
		case service.queue <- record:
		default:
			service.dropped++
		}
	}
	return record, true
}

// reject counts one entry the catalogue refused and always reports false, so
// build can return it directly.
func (service *Service) reject() bool {
	service.mutex.Lock()
	service.dropped++
	service.mutex.Unlock()
	return false
}

// RecentRecords snapshots the newest safe records for a user-requested report.
func (service *Service) RecentRecords(limit int) []Record {
	if service == nil || limit <= 0 {
		return []Record{}
	}
	service.mutex.Lock()
	defer service.mutex.Unlock()
	start := len(service.buffer) - limit
	if start < 0 {
		start = 0
	}
	return append([]Record{}, service.buffer[start:]...)
}

// Records returns a page of the global buffer after cursor, optionally
// filtered by severity. It is a read: nothing is consumed or cleared.
func (service *Service) Records(cursor string, limit int, severity string) (Page, error) {
	if service == nil {
		return Page{Records: []Record{}}, nil
	}
	if limit == 0 {
		limit = 50
	}
	if limit < 1 || limit > 200 {
		return Page{}, fmt.Errorf("limit %d is outside the range 1..200", limit)
	}
	if severity != "" && !allowedSeverities[severity] {
		return Page{}, fmt.Errorf("unknown severity %q", severity)
	}
	var cursorSeq uint64
	hasCursor := false
	if cursor != "" {
		parsed, err := strconv.ParseUint(cursor, 10, 64)
		if err != nil || strconv.FormatUint(parsed, 10) != cursor {
			return Page{}, fmt.Errorf("cursor must be a canonical decimal uint64; got %q", cursor)
		}
		cursorSeq = parsed
		hasCursor = true
	}

	service.mutex.Lock()
	defer service.mutex.Unlock()

	total := len(service.buffer)
	if total == 0 {
		return Page{Records: []Record{}}, nil
	}
	oldest := service.buffer[0].Seq
	newest := service.buffer[total-1].Seq
	// A cursor older than the oldest retained record cannot be continued from:
	// the records between them were evicted, so the caller is told rather than
	// silently handed a gap.
	expired := hasCursor && cursorSeq < oldest-1

	matched := make([]Record, 0, total)
	for _, record := range service.buffer {
		if hasCursor && !expired && record.Seq <= cursorSeq {
			continue
		}
		if severity != "" && record.Severity != severity {
			continue
		}
		matched = append(matched, record)
	}

	page := Page{
		Records:               matched,
		TotalBuffered:         total,
		CursorExpired:         expired,
		OldestAvailableCursor: strconv.FormatUint(oldest, 10),
	}
	if len(matched) > limit {
		page.Records = matched[:limit]
		page.HasMore = true
	}
	if len(page.Records) > 0 {
		page.NextCursor = strconv.FormatUint(page.Records[len(page.Records)-1].Seq, 10)
	} else if hasCursor && !expired {
		page.NextCursor = cursor
	} else {
		page.NextCursor = strconv.FormatUint(newest, 10)
	}
	return page, nil
}

// Close stops the writer within a bounded time. A writer that cannot finish is
// abandoned rather than allowed to hold up the application's exit.
func (service *Service) Close() {
	if service == nil || service.queue == nil {
		return
	}
	service.closeOne.Do(func() {
		service.mutex.Lock()
		service.closed = true
		close(service.queue)
		service.mutex.Unlock()
	})
	select {
	case <-service.done:
	case <-time.After(2 * time.Second):
	}
}

// NewCorrelationID mints the identifier that ties one operation's records
// together. It is random and carries no user, host or save data, so it can
// appear in a log the user shares.
func NewCorrelationID() string {
	var raw [8]byte
	if _, err := rand.Read(raw[:]); err != nil {
		// A failed generator must not stop an operation from being logged; an
		// empty identifier simply means these records cannot be correlated.
		return ""
	}
	return hex.EncodeToString(raw[:])
}
