// Code generated by tools/generate_aow_compat; DO NOT EDIT.
// Sources: tmp/regulation-bin-dump/csv/EquipParamGem.csv (sha256 008d5b0be8c86e1d461de6164b3c49dbc4d9266c75fbc0037578a120f8f40283), tmp/regulation-bin-dump/params/EquipParamGem.param (sha256 dcdc8d9ade2ae3ef6f430d4b568782bca657ff7be34b75f4aba5623e7b82db00), tmp/regulation-bin-dump/csv/EquipParamWeapon.csv (sha256 21dd9565289357563e9d66d0fe3bb019b6a5d64ccaf8480738de028e9cd20ead).
//
// Single source of truth shared with backend/db/data/aow_compat.go. Bits 0..35 come
// from the CSV canMountWep_* columns; bits 36..43 come from the raw PARAM field.

// Maps EquipParamWeapon.wepType to AoWCompatBitmask bit positions.
export const WEP_TYPE_TO_BITS: Record<number, number[]> = {
    1: [0],
    3: [1],
    5: [2],
    7: [3],
    9: [4],
    11: [5],
    13: [6],
    14: [7],
    15: [8],
    16: [9],
    17: [10],
    19: [11],
    21: [12],
    23: [13],
    24: [14],
    25: [15],
    28: [16],
    29: [18],
    31: [19],
    32: [17],
    33: [18],
    35: [20],
    37: [21],
    39: [22],
    41: [23],
    50: [24],
    51: [25],
    53: [26],
    55: [27],
    56: [28],
    57: [29],
    61: [30],
    65: [32],
    67: [33],
    69: [34],
    87: [35],
    88: [36],
    89: [37],
    90: [38],
    91: [39],
    92: [40],
    93: [41],
    94: [42],
    95: [43],
};

// Maps an Ash of War item ID to compatible wepTypes when it has no direct mask bit.
export const AOW_HEURISTIC_WEPTYPES: Record<number, number[]> = {
};
