// Code generated by tools/generate_aow_compat; DO NOT EDIT.
// Sources: tmp/regulation-bin-dump/csv/EquipParamGem.csv (sha256 008d5b0be8c86e1d461de6164b3c49dbc4d9266c75fbc0037578a120f8f40283), tmp/regulation-bin-dump/csv/EquipParamWeapon.csv (sha256 21dd9565289357563e9d66d0fe3bb019b6a5d64ccaf8480738de028e9cd20ead).
//
// Single source of truth shared with backend/db/data/aow_compat.go. Bits 0..35 come
// from EquipParamGem.canMountWep_*, bits 36..39 from reserved_canMountWep. Backhand
// Blades / Light Greatswords and the native arts of Great Katanas / Beast Claws carry
// no direct bit and are resolved via AOW_HEURISTIC_WEPTYPES (heuristic, fail-closed).

// Maps EquipParamWeapon.wepType to AoWCompatBitmask bit positions.
export const WEP_TYPE_TO_BITS: Record<number, number[]> = {
    1: [0],
    3: [1],
    5: [2],
    7: [3],
    9: [8],
    11: [9],
    13: [6],
    14: [5],
    15: [4],
    16: [7],
    17: [7],
    19: [11],
    21: [13],
    23: [10],
    24: [10],
    25: [12],
    28: [14],
    29: [14],
    31: [15],
    32: [17],
    33: [18],
    35: [20],
    37: [19],
    39: [20],
    41: [21],
    43: [22],
    50: [23],
    51: [24],
    52: [25],
    53: [26],
    54: [27],
    55: [28],
    57: [29],
    61: [30],
    65: [32],
    66: [33],
    67: [34],
    69: [34],
    87: [35],
    88: [36],
    89: [37],
    90: [38],
    91: [39],
    94: [6],
    95: [21],
};

// Maps an Ash of War item ID to compatible wepTypes when it has no direct mask bit.
export const AOW_HEURISTIC_WEPTYPES: Record<number, number[]> = {
    0x800631F0: [95],
    0x800635D8: [95],
    0x80063DA8: [92],
    0x80064190: [92],
    0x80064578: [94],
    0x80064960: [93],
};
