// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllGraces() {
  return window['go']['main']['App']['GetAllGraces']();
}

export function GetCharacter(arg1) {
  return window['go']['main']['App']['GetCharacter'](arg1);
}

export function GetItemList(arg1) {
  return window['go']['main']['App']['GetItemList'](arg1);
}

export function GetSteamID() {
  return window['go']['main']['App']['GetSteamID']();
}

export function ImportSlot(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportSlot'](arg1, arg2, arg3);
}

export function OpenSave(arg1) {
  return window['go']['main']['App']['OpenSave'](arg1);
}

export function SaveCharacter(arg1, arg2) {
  return window['go']['main']['App']['SaveCharacter'](arg1, arg2);
}
