// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItemsToCharacter(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['AddItemsToCharacter'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function CloneSlot(arg1, arg2) {
  return window['go']['main']['App']['CloneSlot'](arg1, arg2);
}

export function DeleteSlot(arg1) {
  return window['go']['main']['App']['DeleteSlot'](arg1);
}

export function GetActiveSlots() {
  return window['go']['main']['App']['GetActiveSlots']();
}

export function GetAllGraces() {
  return window['go']['main']['App']['GetAllGraces']();
}

export function GetBosses(arg1) {
  return window['go']['main']['App']['GetBosses'](arg1);
}

export function GetCharacter(arg1) {
  return window['go']['main']['App']['GetCharacter'](arg1);
}

export function GetCharacterNames() {
  return window['go']['main']['App']['GetCharacterNames']();
}

export function GetColosseums(arg1) {
  return window['go']['main']['App']['GetColosseums'](arg1);
}

export function GetGraces(arg1) {
  return window['go']['main']['App']['GetGraces'](arg1);
}

export function GetInfuseTypes() {
  return window['go']['main']['App']['GetInfuseTypes']();
}

export function GetItemList(arg1) {
  return window['go']['main']['App']['GetItemList'](arg1);
}

export function GetMapProgress(arg1) {
  return window['go']['main']['App']['GetMapProgress'](arg1);
}

export function GetSaveDiffSummary() {
  return window['go']['main']['App']['GetSaveDiffSummary']();
}

export function GetSlotCapacity(arg1) {
  return window['go']['main']['App']['GetSlotCapacity'](arg1);
}

export function GetSlotDiff(arg1) {
  return window['go']['main']['App']['GetSlotDiff'](arg1);
}

export function GetSourceActiveSlots() {
  return window['go']['main']['App']['GetSourceActiveSlots']();
}

export function GetSteamID() {
  return window['go']['main']['App']['GetSteamID']();
}

export function GetSteamIDString() {
  return window['go']['main']['App']['GetSteamIDString']();
}

export function GetSummoningPools(arg1) {
  return window['go']['main']['App']['GetSummoningPools'](arg1);
}

export function GetUndoDepth(arg1) {
  return window['go']['main']['App']['GetUndoDepth'](arg1);
}

export function ImportCharacter(arg1, arg2) {
  return window['go']['main']['App']['ImportCharacter'](arg1, arg2);
}

export function RemoveFogOfWar(arg1) {
  return window['go']['main']['App']['RemoveFogOfWar'](arg1);
}

export function RemoveItemsFromCharacter(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RemoveItemsFromCharacter'](arg1, arg2, arg3, arg4);
}

export function ResetMapExploration(arg1) {
  return window['go']['main']['App']['ResetMapExploration'](arg1);
}

export function RevealAllMap(arg1) {
  return window['go']['main']['App']['RevealAllMap'](arg1);
}

export function RevertSlot(arg1) {
  return window['go']['main']['App']['RevertSlot'](arg1);
}

export function SaveCharacter(arg1, arg2) {
  return window['go']['main']['App']['SaveCharacter'](arg1, arg2);
}

export function SelectAndOpenSave() {
  return window['go']['main']['App']['SelectAndOpenSave']();
}

export function SelectAndOpenSourceSave() {
  return window['go']['main']['App']['SelectAndOpenSourceSave']();
}

export function SetBossDefeated(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetBossDefeated'](arg1, arg2, arg3);
}

export function SetColosseumUnlocked(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetColosseumUnlocked'](arg1, arg2, arg3);
}

export function SetGraceVisited(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetGraceVisited'](arg1, arg2, arg3);
}

export function SetMapFlag(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetMapFlag'](arg1, arg2, arg3);
}

export function SetMapRegionFlags(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetMapRegionFlags'](arg1, arg2, arg3);
}

export function SetSlotActivity(arg1, arg2) {
  return window['go']['main']['App']['SetSlotActivity'](arg1, arg2);
}

export function SetSteamID(arg1) {
  return window['go']['main']['App']['SetSteamID'](arg1);
}

export function SetSteamIDFromString(arg1) {
  return window['go']['main']['App']['SetSteamIDFromString'](arg1);
}

export function SetSummoningPoolActivated(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSummoningPoolActivated'](arg1, arg2, arg3);
}

export function WriteSave(arg1) {
  return window['go']['main']['App']['WriteSave'](arg1);
}
