// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {vm} from '../models';

export function GetAllGraces():Promise<Array<db.GraceEntry>>;

export function GetCharacter(arg1:number):Promise<vm.CharacterViewModel>;

export function GetItemList(arg1:string):Promise<Array<db.ItemEntry>>;

export function GetSteamID():Promise<number>;

export function ImportSlot(arg1:string,arg2:number,arg3:number):Promise<void>;

export function OpenSave(arg1:string):Promise<string>;

export function SaveCharacter(arg1:number,arg2:vm.CharacterViewModel):Promise<void>;
