// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCharacter(arg1) {
  return window['go']['main']['App']['GetCharacter'](arg1);
}

export function GetSteamID() {
  return window['go']['main']['App']['GetSteamID']();
}

export function OpenSave(arg1) {
  return window['go']['main']['App']['OpenSave'](arg1);
}

export function SaveCharacter(arg1, arg2) {
  return window['go']['main']['App']['SaveCharacter'](arg1, arg2);
}
